### PR TITLE
Ansible-playbook for verifying the kubectl-drain behaviour with opene…

### PR DESCRIPTION
**Pull request by Swarnalatha-K**
…bs volume replicas running on nodes

Signed-off-by: swarna <swarnalatha@cloudbyte.com>

**What this PR does / why we need it**:
   Verifying the kubectl-drain behaviour with openebs volume replicas running on nodes with node affenity.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:
@ksatchit Plese review this PR.

### CODE REVIEW

**Comment by Swarnalatha-K** [comment]
Test output:
```
TASK [Get $HOME of K8s master for kubernetes user] *********************************************************************************************************************
task path: /home/devops/openebs/e2e/ansible/playbooks/hyperconverged/test-k8s-drain-nodes/test-drain-nodes.yml:28
changed: [localhost -> None] => {"changed": true, "cmd": "source ~/.profile; echo $HOME", "delta": "0:00:00.009611", "end": "2018-05-07 05:35:09.607295", "rc": 0, "start": "2018-05-07 05:35:09.597684", "stderr": "", "stderr_lines": [], "stdout": "/home/ubuntu", "stdout_lines": ["/home/ubuntu"]}

TASK [Get the Number of nodes count] ***********************************************************************************************************************************
task path: /home/devops/openebs/e2e/ansible/playbooks/hyperconverged/test-k8s-drain-nodes/test-drain-nodes.yml:35
changed: [localhost -> None] => {"changed": true, "cmd": "source ~/.profile; kubectl get nodes | grep 'Ready' | grep 'none' | wc -l", "delta": "0:00:00.447400", "end": "2018-05-07 05:35:10.588178", "rc": 0, "start": "2018-05-07 05:35:10.140778", "stderr": "", "stderr_lines": [], "stdout": "3", "stdout_lines": ["3"]}

TASK [Fetch the node count from stdout] ********************************************************************************************************************************
task path: /home/devops/openebs/e2e/ansible/playbooks/hyperconverged/test-k8s-drain-nodes/test-drain-nodes.yml:42
ok: [localhost] => {"ansible_facts": {"node_count": " 3"}, "changed": false}

TASK [Check whether maya-apiserver pod is deployed] ********************************************************************************************************************
task path: /home/devops/openebs/e2e/ansible/playbooks/hyperconverged/test-k8s-drain-nodes/test-drain-nodes.yml:47
changed: [localhost -> None] => {"attempts": 1, "changed": true, "cmd": "source ~/.profile; kubectl get pods --all-namespaces | grep maya-apiserver", "delta": "0:00:00.548464", "end": "2018-05-07 05:35:11.814833", "rc": 0, "start": "2018-05-07 05:35:11.266369", "stderr": "", "stderr_lines": [], "stdout": "default       maya-apiserver-69f9db69-kpjzc           1/1       Running   0          48s", "stdout_lines": ["default       maya-apiserver-69f9db69-kpjzc           1/1       Running   0          48s"]}

TASK [Start the log aggregator to capture test pod logs] ***************************************************************************************************************
task path: /home/devops/openebs/e2e/ansible/playbooks/hyperconverged/test-k8s-drain-nodes/test-drain-nodes.yml:57
changed: [localhost -> None] => {"changed": true, "cmd": "source ~/.profile; nohup stern \"maya*|openebs*|pvc*|percona*\" --since 1m > \"/home/ubuntu/setup/logs/kubectl-drain-behaviour.log\" &", "delta": "0:00:01.023498", "end": "2018-05-07 05:35:13.391334", "rc": 0, "start": "2018-05-07 05:35:12.367836", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}

TASK [Obtaining storage classes yaml] **********************************************************************************************************************************
task path: /home/devops/openebs/e2e/ansible/playbooks/hyperconverged/test-k8s-drain-nodes/test-drain-nodes.yml:65
changed: [localhost -> None] => {"changed": true, "cmd": "kubectl get sc openebs-percona -o yaml > \"storage-class.yml\"", "delta": "0:00:00.418917", "end": "2018-05-07 05:35:14.422530", "rc": 0, "start": "2018-05-07 05:35:14.003613", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}

TASK [Replace the replica count in openebs-storageclasses yaml] ********************************************************************************************************
task path: /home/devops/openebs/e2e/ansible/playbooks/hyperconverged/test-k8s-drain-nodes/test-drain-nodes.yml:71
ok: [localhost -> None] => {"changed": false, "msg": ""}

TASK [Delete the existing storage class and create new one] ************************************************************************************************************
task path: /home/devops/openebs/e2e/ansible/playbooks/hyperconverged/test-k8s-drain-nodes/test-drain-nodes.yml:78
changed: [localhost -> None] => {"attempts": 1, "changed": true, "cmd": "kubectl delete sc openebs-percona; kubectl apply -f \"storage-class.yml\"", "delta": "0:00:00.945956", "end": "2018-05-07 05:35:16.691317", "rc": 0, "start": "2018-05-07 05:35:15.745361", "stderr": "", "stderr_lines": [], "stdout": "storageclass \"openebs-percona\" deleted\nstorageclass \"openebs-percona\" created", "stdout_lines": ["storageclass \"openebs-percona\" deleted", "storageclass \"openebs-percona\" created"]}

TASK [Deploy percona application] **************************************************************************************************************************************
task path: /home/devops/openebs/e2e/ansible/playbooks/hyperconverged/test-k8s-drain-nodes/test-drain-nodes.yml:90
changed: [localhost -> None] => {"changed": true, "cmd": "source ~/.profile; kubectl apply -f https://raw.githubusercontent.com/openebs/openebs/master/k8s/demo/percona/percona-openebs-deployment.yaml", "delta": "0:00:02.016281", "end": "2018-05-07 05:35:19.270818", "rc": 0, "start": "2018-05-07 05:35:17.254537", "stderr": "", "stderr_lines": [], "stdout": "deployment \"percona\" created\npersistentvolumeclaim \"demo-vol1-claim\" created\nservice \"percona-mysql\" created", "stdout_lines": ["deployment \"percona\" created", "persistentvolumeclaim \"demo-vol1-claim\" created", "service \"percona-mysql\" created"]}

TASK [Confirm if the percona pod is running] ***************************************************************************************************************************
task path: /home/devops/openebs/e2e/ansible/playbooks/hyperconverged/test-k8s-drain-nodes/test-drain-nodes.yml:96
FAILED - RETRYING: Confirm if the percona pod is running (10 retries left).
FAILED - RETRYING: Confirm if the percona pod is running (9 retries left).
changed: [localhost -> None] => {"attempts": 3, "changed": true, "cmd": "source ~/.profile; kubectl get pods --all-namespaces | grep percona", "delta": "0:00:00.774758", "end": "2018-05-07 05:39:26.248976", "rc": 0, "start": "2018-05-07 05:39:25.474218", "stderr": "", "stderr_lines": [], "stdout": "default       percona-c8d49fd55-qthlc                                          1/1       Running   0          2m", "stdout_lines": ["default       percona-c8d49fd55-qthlc                                          1/1       Running   0          2m"]}

TASK [Check if the replica pods are created and running] ***************************************************************************************************************
task path: /home/devops/openebs/e2e/ansible/playbooks/hyperconverged/test-k8s-drain-nodes/test-drain-nodes.yml:106
changed: [localhost -> None] => {"attempts": 1, "changed": true, "cmd": "source ~/.profile; kubectl get pods --all-namespaces | grep rep | grep -i running |wc -l", "delta": "0:00:00.745216", "end": "2018-05-07 05:39:27.628618", "rc": 0, "start": "2018-05-07 05:39:26.883402", "stderr": "", "stderr_lines": [], "stdout": "2", "stdout_lines": ["2"]}

TASK [Get PV name] *****************************************************************************************************************************************************
task path: /home/devops/openebs/e2e/ansible/playbooks/hyperconverged/test-k8s-drain-nodes/test-drain-nodes.yml:118
changed: [localhost -> None] => {"changed": true, "cmd": "source ~/.profile; kubectl get pv | grep openebs-percona | awk '{print $1}'", "delta": "0:00:00.545415", "end": "2018-05-07 05:39:28.752013", "rc": 0, "start": "2018-05-07 05:39:28.206598", "stderr": "", "stderr_lines": [], "stdout": "pvc-6da91187-51b8-11e8-9bc0-02b983f0a4db\npvc-87a028e2-4f8f-11e8-a4e6-02b983f0a4db\npvc-fa38990e-4f80-11e8-abb2-02b983f0a4db", "stdout_lines": ["pvc-6da91187-51b8-11e8-9bc0-02b983f0a4db", "pvc-87a028e2-4f8f-11e8-a4e6-02b983f0a4db", "pvc-fa38990e-4f80-11e8-abb2-02b983f0a4db"]}

TASK [Copy replica_patch.yaml to master] *******************************************************************************************************************************
task path: /home/devops/openebs/e2e/ansible/playbooks/hyperconverged/test-k8s-drain-nodes/test-drain-nodes.yml:126
changed: [localhost -> None] => {"changed": true, "checksum": "6c1b0a07601d8a40ec5b7d8b66fabd310d1d47c9", "dest": "/home/ubuntu/replica_patch.yaml", "gid": 1000, "group": "ubuntu", "md5sum": "00730266803f0063024795e2cb628c1b", "mode": "0664", "owner": "ubuntu", "size": 406, "src": "/home/ubuntu/.ansible/tmp/ansible-tmp-1525671569.54-21754757597457/source", "state": "file", "uid": 1000}

TASK [Get the node name where replica1 is scheduled] *******************************************************************************************************************
task path: /home/devops/openebs/e2e/ansible/playbooks/hyperconverged/test-k8s-drain-nodes/test-drain-nodes.yml:132
changed: [localhost -> None] => {"changed": true, "cmd": "source ~/.profile; kubectl get po --all-namespaces -o wide | grep \"pvc-6da91187-51b8-11e8-9bc0-02b983f0a4db\npvc-87a028e2-4f8f-11e8-a4e6-02b983f0a4db\npvc-fa38990e-4f80-11e8-abb2-02b983f0a4db\" | grep rep | awk '{print $8}' | awk 'FNR == 1 {print}'", "delta": "0:00:00.686337", "end": "2018-05-07 05:39:31.873906", "rc": 0, "start": "2018-05-07 05:39:31.187569", "stderr": "", "stderr_lines": [], "stdout": "kubeminion-02", "stdout_lines": ["kubeminion-02"]}

TASK [Get the node name where replica2 is scheduled] *******************************************************************************************************************
task path: /home/devops/openebs/e2e/ansible/playbooks/hyperconverged/test-k8s-drain-nodes/test-drain-nodes.yml:140
changed: [localhost -> None] => {"changed": true, "cmd": "source ~/.profile; kubectl get po --all-namespaces -o wide | grep \"pvc-6da91187-51b8-11e8-9bc0-02b983f0a4db\npvc-87a028e2-4f8f-11e8-a4e6-02b983f0a4db\npvc-fa38990e-4f80-11e8-abb2-02b983f0a4db\" | grep rep | awk '{print $8}' | awk 'FNR == 2 {print}'", "delta": "0:00:00.839207", "end": "2018-05-07 05:39:33.285635", "rc": 0, "start": "2018-05-07 05:39:32.446428", "stderr": "", "stderr_lines": [], "stdout": "kubeminion-03", "stdout_lines": ["kubeminion-03"]}

TASK [Update replica1 node name in replica_patch file] *****************************************************************************************************************
task path: /home/devops/openebs/e2e/ansible/playbooks/hyperconverged/test-k8s-drain-nodes/test-drain-nodes.yml:148
changed: [localhost -> None] => {"changed": true, "msg": "1 replacements made"}

TASK [Update replica2 node name in replica_patch file] *****************************************************************************************************************
task path: /home/devops/openebs/e2e/ansible/playbooks/hyperconverged/test-k8s-drain-nodes/test-drain-nodes.yml:156
changed: [localhost -> None] => {"changed": true, "msg": "1 replacements made"}

TASK [Get the deployment namee] ****************************************************************************************************************************************
task path: /home/devops/openebs/e2e/ansible/playbooks/hyperconverged/test-k8s-drain-nodes/test-drain-nodes.yml:164
changed: [localhost -> None] => {"changed": true, "cmd": "source ~/.profile; kubectl get deploy --all-namespaces |grep \"pvc-6da91187-51b8-11e8-9bc0-02b983f0a4db\npvc-87a028e2-4f8f-11e8-a4e6-02b983f0a4db\npvc-fa38990e-4f80-11e8-abb2-02b983f0a4db\" | grep rep |awk '{print $2}'", "delta": "0:00:00.697088", "end": "2018-05-07 05:39:35.914031", "rc": 0, "start": "2018-05-07 05:39:35.216943", "stderr": "", "stderr_lines": [], "stdout": "pvc-6da91187-51b8-11e8-9bc0-02b983f0a4db-rep", "stdout_lines": ["pvc-6da91187-51b8-11e8-9bc0-02b983f0a4db-rep"]}

TASK [Apply the node affinity property] ********************************************************************************************************************************
task path: /home/devops/openebs/e2e/ansible/playbooks/hyperconverged/test-k8s-drain-nodes/test-drain-nodes.yml:172
changed: [localhost -> None] => {"attempts": 1, "changed": true, "cmd": "source ~/.profile; kubectl patch deployment \"pvc-6da91187-51b8-11e8-9bc0-02b983f0a4db-rep\" -p \"$(cat replica_patch.yaml)\"", "delta": "0:00:00.535076", "end": "2018-05-07 05:39:37.096288", "rc": 0, "start": "2018-05-07 05:39:36.561212", "stderr": "", "stderr_lines": [], "stdout": "deployment \"pvc-6da91187-51b8-11e8-9bc0-02b983f0a4db-rep\" patched", "stdout_lines": ["deployment \"pvc-6da91187-51b8-11e8-9bc0-02b983f0a4db-rep\" patched"]}

TASK [Drain the node where replica is scheduled] ***********************************************************************************************************************
task path: /home/devops/openebs/e2e/ansible/playbooks/hyperconverged/test-k8s-drain-nodes/test-drain-nodes.yml:183
changed: [localhost -> None] => {"changed": true, "cmd": "source ~/.profile; kubectl drain kubeminion-02 --ignore-daemonsets --force", "delta": "0:00:05.052145", "end": "2018-05-07 05:39:42.871358", "rc": 0, "start": "2018-05-07 05:39:37.819213", "stderr": "WARNING: Ignoring DaemonSet-managed pods: kube-proxy-sw9kc, weave-net-z67qq", "stderr_lines": ["WARNING: Ignoring DaemonSet-managed pods: kube-proxy-sw9kc, weave-net-z67qq"], "stdout": "node \"kubeminion-02\" cordoned\npod \"maya-apiserver-69f9db69-gxb8m\" evicted\npod \"maya-apiserver-69f9db69-tp7zh\" evicted\npod \"pvc-6da91187-51b8-11e8-9bc0-02b983f0a4db-rep-85b94c77bf-f988f\" evicted\npod \"openebs-provisioner-77cb47986c-snc84\" evicted\nnode \"kubeminion-02\" drained", "stdout_lines": ["node \"kubeminion-02\" cordoned", "pod \"maya-apiserver-69f9db69-gxb8m\" evicted", "pod \"maya-apiserver-69f9db69-tp7zh\" evicted", "pod \"pvc-6da91187-51b8-11e8-9bc0-02b983f0a4db-rep-85b94c77bf-f988f\" evicted", "pod \"openebs-provisioner-77cb47986c-snc84\" evicted", "node \"kubeminion-02\" drained"]}

TASK [Check the available replicas in deployment] **********************************************************************************************************************
task path: /home/devops/openebs/e2e/ansible/playbooks/hyperconverged/test-k8s-drain-nodes/test-drain-nodes.yml:193
FAILED - RETRYING: Check the available replicas in deployment (5 retries left).
FAILED - RETRYING: Check the available replicas in deployment (4 retries left).
FAILED - RETRYING: Check the available replicas in deployment (3 retries left).
FAILED - RETRYING: Check the available replicas in deployment (2 retries left).
FAILED - RETRYING: Check the available replicas in deployment (1 retries left).
fatal: [localhost -> None]: FAILED! => {"attempts": 5, "changed": true, "cmd": "kubectl get deploy --all-namespaces | grep \"pvc-6da91187-51b8-11e8-9bc0-02b983f0a4db\npvc-87a028e2-4f8f-11e8-a4e6-02b983f0a4db\npvc-fa38990e-4f80-11e8-abb2-02b983f0a4db\" | grep rep | awk '{print $6}'", "delta": "0:00:00.715070", "end": "2018-05-07 05:42:19.959822", "rc": 0, "start": "2018-05-07 05:42:19.244752", "stderr": "", "stderr_lines": [], "stdout": "1", "stdout_lines": ["1"]}
...ignoring

TASK [Check if the replica is in pending state] ************************************************************************************************************************
task path: /home/devops/openebs/e2e/ansible/playbooks/hyperconverged/test-k8s-drain-nodes/test-drain-nodes.yml:205
changed: [localhost -> None] => {"attempts": 1, "changed": true, "cmd": "kubectl get pods --all-namespaces -o wide | grep \"pvc-6da91187-51b8-11e8-9bc0-02b983f0a4db\npvc-87a028e2-4f8f-11e8-a4e6-02b983f0a4db\npvc-fa38990e-4f80-11e8-abb2-02b983f0a4db\" | grep rep | grep Pending", "delta": "0:00:00.688179", "end": "2018-05-07 05:42:21.208292", "rc": 0, "start": "2018-05-07 05:42:20.520113", "stderr": "", "stderr_lines": [], "stdout": "default       pvc-6da91187-51b8-11e8-9bc0-02b983f0a4db-rep-5b767f8874-cqhh6    0/1       Pending   0          2m        <none>         <none>", "stdout_lines": ["default       pvc-6da91187-51b8-11e8-9bc0-02b983f0a4db-rep-5b767f8874-cqhh6    0/1       Pending   0          2m        <none>         <none>"]}

TASK [Terminate the log aggregator] ************************************************************************************************************************************
task path: /home/devops/openebs/e2e/ansible/playbooks/hyperconverged/test-k8s-drain-nodes/test-drain-nodes.yml:215
changed: [localhost -> None] => {"changed": true, "cmd": "source ~/.profile; killall stern", "delta": "0:00:00.033477", "end": "2018-05-07 05:42:21.837494", "rc": 0, "start": "2018-05-07 05:42:21.804017", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}

TASK [Set flag to pass if test case is passed] *************************************************************************************************************************
task path: /home/devops/openebs/e2e/ansible/playbooks/hyperconverged/test-k8s-drain-nodes/test-drain-nodes.yml:221
ok: [localhost] => {"ansible_facts": {"flag": "Pass"}, "changed": false}

TASK [Delete Percona deployment] ***************************************************************************************************************************************
task path: /home/devops/openebs/e2e/ansible/playbooks/hyperconverged/test-k8s-drain-nodes/cleanup.yml:2
changed: [localhost -> None] => {"attempts": 1, "changed": true, "cmd": "source ~/.profile; kubectl delete -f \"https://raw.githubusercontent.com/openebs/openebs/master/k8s/demo/percona/percona-openebs-deployment.yaml\"", "delta": "0:00:05.251209", "end": "2018-05-07 05:42:27.723827", "rc": 0, "start": "2018-05-07 05:42:22.472618", "stderr": "", "stderr_lines": [], "stdout": "deployment \"percona\" deleted\npersistentvolumeclaim \"demo-vol1-claim\" deleted\nservice \"percona-mysql\" deleted", "stdout_lines": ["deployment \"percona\" deleted", "persistentvolumeclaim \"demo-vol1-claim\" deleted", "service \"percona-mysql\" deleted"]}

TASK [Confirm percona pod has been deleted] ****************************************************************************************************************************
task path: /home/devops/openebs/e2e/ansible/playbooks/hyperconverged/test-k8s-drain-nodes/cleanup.yml:13
FAILED - RETRYING: Confirm percona pod has been deleted (10 retries left).
changed: [localhost -> None] => {"attempts": 2, "changed": true, "cmd": "source ~/.profile; kubectl get pods --all-namespaces -l name=percona", "delta": "0:00:00.388183", "end": "2018-05-07 05:42:59.750630", "rc": 0, "start": "2018-05-07 05:42:59.362447", "stderr": "No resources found.", "stderr_lines": ["No resources found."], "stdout": "", "stdout_lines": []}

TASK [uncordon the node which is drained] ******************************************************************************************************************************
task path: /home/devops/openebs/e2e/ansible/playbooks/hyperconverged/test-k8s-drain-nodes/cleanup.yml:24
changed: [localhost -> None] => {"attempts": 1, "changed": true, "cmd": "source ~/.profile; kubectl uncordon kubeminion-02", "delta": "0:00:00.413058", "end": "2018-05-07 05:43:00.746154", "rc": 0, "start": "2018-05-07 05:43:00.333096", "stderr": "", "stderr_lines": [], "stdout": "node \"kubeminion-02\" uncordoned", "stdout_lines": ["node \"kubeminion-02\" uncordoned"]}

TASK [Remove test artifacts] *******************************************************************************************************************************************
task path: /home/devops/openebs/e2e/ansible/playbooks/hyperconverged/test-k8s-drain-nodes/cleanup.yml:36
changed: [localhost -> None] => (item=storage-class.yml) => {"changed": true, "item": "storage-class.yml", "path": "/home/ubuntu/storage-class.yml", "state": "absent"}
changed: [localhost -> None] => (item=replica_patch.yaml) => {"changed": true, "item": "replica_patch.yaml", "path": "/home/ubuntu/replica_patch.yaml", "state": "absent"}
```

**Comment by Swarnalatha-K** [comment]
Stern logs:
```
+ openebs-provisioner-77cb47986c-snc84 › openebs-provisioner
+ maya-apiserver-69f9db69-kpjzc › maya-apiserver
openebs-provisioner-77cb47986c-snc84 openebs-provisioner I0507 05:34:49.717283       1 maya_api.go:63] OpenEBS volume provisioner namespace default
openebs-provisioner-77cb47986c-snc84 openebs-provisioner I0507 05:34:49.745016       1 controller.go:407] Starting provisioner controller 5c313e1d-51b8-11e8-8ee4-121592e74a62!
openebs-provisioner-77cb47986c-snc84 openebs-provisioner I0507 05:35:04.817246       1 controller.go:1080] scheduleOperation[delete-pvc-87a028e2-4f8f-11e8-a4e6-02b983f0a4db[88921288-4f8f-11e8-a4e6-02b983f0a4db]]
openebs-provisioner-77cb47986c-snc84 openebs-provisioner I0507 05:35:04.817355       1 controller.go:1080] scheduleOperation[delete-pvc-fa38990e-4f80-11e8-abb2-02b983f0a4db[fb853c8b-4f80-11e8-abb2-02b983f0a4db]]
openebs-provisioner-77cb47986c-snc84 openebs-provisioner I0507 05:35:04.817373       1 controller.go:1080] scheduleOperation[delete-pvc-11f00ac0-4f62-11e8-acb3-02b983f0a4db[12877345-4f62-11e8-acb3-02b983f0a4db]]
openebs-provisioner-77cb47986c-snc84 openebs-provisioner I0507 05:35:04.831365       1 controller.go:1047] deletion of volume "pvc-fa38990e-4f80-11e8-abb2-02b983f0a4db" ignored: ignored because identity annotation on PV does not match ours
openebs-provisioner-77cb47986c-snc84 openebs-provisioner I0507 05:35:04.844891       1 controller.go:1047] deletion of volume "pvc-87a028e2-4f8f-11e8-a4e6-02b983f0a4db" ignored: ignored because identity annotation on PV does not match ours
openebs-provisioner-77cb47986c-snc84 openebs-provisioner I0507 05:35:05.226415       1 maya_api.go:205] volume Deleted Successfully initiated
openebs-provisioner-77cb47986c-snc84 openebs-provisioner I0507 05:35:05.226475       1 controller.go:1056] volume "pvc-11f00ac0-4f62-11e8-acb3-02b983f0a4db" deleted
openebs-provisioner-77cb47986c-snc84 openebs-provisioner I0507 05:35:05.259822       1 controller.go:1067] volume "pvc-11f00ac0-4f62-11e8-acb3-02b983f0a4db" deleted from database
maya-apiserver-69f9db69-kpjzc maya-apiserver + MAYA_API_SERVER_NETWORK=eth0
maya-apiserver-69f9db69-kpjzc maya-apiserver + ip -4 addr show scope global dev eth0
maya-apiserver-69f9db69-kpjzc maya-apiserver + grep inet
maya-apiserver-69f9db69-kpjzc maya-apiserver + awk {print $2}
maya-apiserver-69f9db69-kpjzc maya-apiserver + cut -d / -f 1
maya-apiserver-69f9db69-kpjzc maya-apiserver + CONTAINER_IP_ADDR=10.44.0.5
maya-apiserver-69f9db69-kpjzc maya-apiserver + exec /usr/local/bin/maya-apiserver start --bind=10.44.0.5
maya-apiserver-69f9db69-kpjzc maya-apiserver I0507 05:34:49.804083       6 start.go:122] Initializing maya-apiserver...
maya-apiserver-69f9db69-kpjzc maya-apiserver I0507 05:34:49.804556       6 start.go:231] Starting maya api server ...
maya-apiserver-69f9db69-kpjzc maya-apiserver I0507 05:34:49.804574       6 registry.go:50] Registered 'kubernetes' as orchestration provider
maya-apiserver-69f9db69-kpjzc maya-apiserver I0507 05:34:49.804589       6 registry.go:50] Registered 'nomad' as orchestration provider
maya-apiserver-69f9db69-kpjzc maya-apiserver I0507 05:34:49.805970       6 start.go:160] Maya api server configuration:
maya-apiserver-69f9db69-kpjzc maya-apiserver I0507 05:34:49.806030       6 start.go:162]          Log Level: INFO
maya-apiserver-69f9db69-kpjzc maya-apiserver I0507 05:34:49.806039       6 start.go:162]             Region: global (DC: dc1)
maya-apiserver-69f9db69-kpjzc maya-apiserver I0507 05:34:49.806046       6 start.go:162]            Version: v0.5.1-pre-release
maya-apiserver-69f9db69-kpjzc maya-apiserver I0507 05:34:49.806051       6 start.go:168]
maya-apiserver-69f9db69-kpjzc maya-apiserver I0507 05:34:49.806057       6 start.go:171] Maya api server started! Log data will stream in below:
maya-apiserver-69f9db69-kpjzc maya-apiserver 2018/05/07 05:35:04.546837 [DEBUG] http: Request /latest/volumes/delete/pvc-11f00ac0-4f62-11e8-acb3-02b983f0a4db (GET)
maya-apiserver-69f9db69-kpjzc maya-apiserver [DEBUG] Processing GET request
maya-apiserver-69f9db69-kpjzc maya-apiserver I0507 05:35:04.546901       6 volume_endpoint.go:196] Processing Volume delete request
maya-apiserver-69f9db69-kpjzc maya-apiserver I0507 05:35:04.547019       6 util.go:1205] Will use env var 'DEFAULT_PVP_NAME: '
maya-apiserver-69f9db69-kpjzc maya-apiserver I0507 05:35:04.547033       6 jiva.go:56] Building new instance of jiva persistent volume provisioner 'volumeprovisioner.mapi.openebs.io/name:jiva'
maya-apiserver-69f9db69-kpjzc maya-apiserver I0507 05:35:04.547066       6 util.go:1205] Will use env var 'DEFAULT_ORCHESTRATOR_NAME: '
"kubectl-drain-behaviour.log" 1079L, 297091C 
openebs-provisioner-77cb47986c-snc84 openebs-provisioner I0507 05:35:34.852965       1 controller.go:1047] deletion of volume "pvc-87a028e2-4f8f-11e8-a4e6-02b983f0a4db" ignored: ignored because identity annotation on PV does not match ours
+ pvc-6da91187-51b8-11e8-9bc0-02b983f0a4db-ctrl-67fbd46fd9-wpwct › maya-volume-exporter
+ pvc-6da91187-51b8-11e8-9bc0-02b983f0a4db-ctrl-67fbd46fd9-wpwct › pvc-6da91187-51b8-11e8-9bc0-02b983f0a4db-ctrl-con
pvc-6da91187-51b8-11e8-9bc0-02b983f0a4db-ctrl-67fbd46fd9-wpwct pvc-6da91187-51b8-11e8-9bc0-02b983f0a4db-ctrl-con mount: special device /host/dev does not exist
pvc-6da91187-51b8-11e8-9bc0-02b983f0a4db-ctrl-67fbd46fd9-wpwct maya-volume-exporter I0507 05:35:41.099120       1 command.go:70] Starting maya-volume-exporter ...
pvc-6da91187-51b8-11e8-9bc0-02b983f0a4db-ctrl-67fbd46fd9-wpwct maya-volume-exporter I0507 05:35:41.108284       1 logs.go:43] Starting Server: :9500
pvc-6da91187-51b8-11e8-9bc0-02b983f0a4db-ctrl-67fbd46fd9-wpwct pvc-6da91187-51b8-11e8-9bc0-02b983f0a4db-ctrl-con time="2018-05-07T05:35:23Z" level=info msg="Listening on :9501"
openebs-provisioner-77cb47986c-snc84 openebs-provisioner I0507 05:35:49.820209       1 controller.go:1080] scheduleOperation[delete-pvc-87a028e2-4f8f-11e8-a4e6-02b983f0a4db[88921288-4f8f-11e8-a4e6-02b983f0a4db]]
openebs-provisioner-77cb47986c-snc84 openebs-provisioner I0507 05:35:49.820297       1 controller.go:1080] scheduleOperation[delete-pvc-fa38990e-4f80-11e8-abb2-02b983f0a4db[fb853c8b-4f80-11e8-abb2-02b983f0a4db]]
openebs-provisioner-77cb47986c-snc84 openebs-provisioner I0507 05:35:49.834397       1 controller.go:1047] deletion of volume "pvc-fa38990e-4f80-11e8-abb2-02b983f0a4db" ignored: ignored because identity annotation on PV does not match ours
openebs-provisioner-77cb47986c-snc84 openebs-provisioner I0507 05:35:49.837264       1 controller.go:1047] deletion of volume "pvc-87a028e2-4f8f-11e8-a4e6-02b983f0a4db" ignored: ignored because identity annotation on PV does not match ours
+ pvc-6da91187-51b8-11e8-9bc0-02b983f0a4db-rep-85b94c77bf-f988f › pvc-6da91187-51b8-11e8-9bc0-02b983f0a4db-rep-con
pvc-6da91187-51b8-11e8-9bc0-02b983f0a4db-rep-85b94c77bf-f988f pvc-6da91187-51b8-11e8-9bc0-02b983f0a4db-rep-con time="2018-05-07T05:35:56Z" level=info msg="Creating volume /openebs, size 5368709120/512"
pvc-6da91187-51b8-11e8-9bc0-02b983f0a4db-rep-85b94c77bf-f988f pvc-6da91187-51b8-11e8-9bc0-02b983f0a4db-rep-con time="2018-05-07T05:35:56Z" level=info msg="Listening on data 10.36.0.6:9503"
pvc-6da91187-51b8-11e8-9bc0-02b983f0a4db-rep-85b94c77bf-f988f pvc-6da91187-51b8-11e8-9bc0-02b983f0a4db-rep-con time="2018-05-07T05:35:56Z" level=info msg="Listening on control 10.36.0.6:9502"
pvc-6da91187-51b8-11e8-9bc0-02b983f0a4db-rep-85b94c77bf-f988f pvc-6da91187-51b8-11e8-9bc0-02b983f0a4db-rep-con time="2018-05-07T05:35:56Z" level=info msg="Listening on sync 10.36.0.6:9504"
+ pvc-6da91187-51b8-11e8-9bc0-02b983f0a4db-rep-85b94c77bf-9tsvr › pvc-6da91187-51b8-11e8-9bc0-02b983f0a4db-rep-con
pvc-6da91187-51b8-11e8-9bc0-02b983f0a4db-rep-85b94c77bf-9tsvr pvc-6da91187-51b8-11e8-9bc0-02b983f0a4db-rep-con time="2018-05-07T05:35:57Z" level=info msg="Creating volume /openebs, size 5368709120/512"
pvc-6da91187-51b8-11e8-9bc0-02b983f0a4db-rep-85b94c77bf-9tsvr pvc-6da91187-51b8-11e8-9bc0-02b983f0a4db-rep-con time="2018-05-07T05:35:57Z" level=info msg="Listening on data 10.44.0.6:9503"
pvc-6da91187-51b8-11e8-9bc0-02b983f0a4db-rep-85b94c77bf-9tsvr pvc-6da91187-51b8-11e8-9bc0-02b983f0a4db-rep-con time="2018-05-07T05:35:57Z" level=info msg="Listening on control 10.44.0.6:9502"
```

**Comment by Swarnalatha-K** [comment]
Ansible-lint report:
```
devops@devops-virtual-machine:~/openebs/e2e/ansible/playbooks/hyperconverged/test-k8s-drain-nodes$ ansible-lint test-drain-nodes.yml
devops@devops-virtual-machine:~/openebs/e2e/ansible/playbooks/hyperconverged/test-k8s-drain-nodes$
devops@devops-virtual-machine:~/openebs/e2e/ansible/playbooks/hyperconverged/test-k8s-drain-nodes$
```

**Comment by ksatchit** [comment]
@Swarnalatha-K , Can you please place more details in the PR - the test intention, approach taken to test, expected output, current behaviour etc..,

**Comment by Swarnalatha-K** [comment]
### Test approach:  With Node affinity, Drain the node using kubectl drain command and check wether the replicas are going to pending state or re-scheduling on other nodes.
### Expected output:
Once you drain the node, replicas should go to pending state. should not schedule on other nodes with node affinity.
### Current behaviour:
Replicas are going to pending state after node drain.

**Comment by Swarnalatha-K** [comment]
@ksatchit included test approach, expected result and current behaviour ot the test.

**Pull request merged**
