### PR TITLE
Corrected git commands

### PR DESCRIPTION
**Pull request by Taranzz25**
Some Git commands were incorrect as they were literal translations of english commands and hence incorrect. Issue #3291

### CODE REVIEW

**Review by kmova — APPROVED** [review]

**Comment by kmova** [comment]
thank you for this PR, can you please sign off the commit with your email id as described here:
https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md#sign-your-work

**Comment by Taranzz25** [comment]
Hi @kmova ,

For the last hour I am trying to add a sign off and pass this check, but at the last step I am unable to push the changes due to the following error: 
`remote: Permission to openebs/openebs.git denied to Taranzz25.`     
`fatal: unable to access 'https://github.com/openebs/openebs/': The requested URL returned error: 403`

Will it be okay if I raise another PR (with a sign off) and you merge that one instead? I will add a comment containing the new PR's link here. Also I am not sure if it would be counted as a hacktoberfest PR or not. Would it?

Thank you

**Comment by kmova** [comment]
You can raise another PR or comment on this PR with your email id.

**Comment by Taranzz25** [comment]
Signed-off-by: Taranjot Singh <taranzz25@gmail.com>

**Review by kmova — APPROVED** [review]

**Comment by kmova** [comment]
You can sign up for Hacktoberfest swag from MayaData by entering details here: https://github.com/mayadata-io/swag/issues/new/choose

**Pull request merged**
