### PR TITLE
gh-1528: Fix mix-indent in openebs/k8s/vagrant/1.9.4/ubuntu/Vagrantfile

### LINKED ISSUE #1528: Fix mix-indent in openebs/k8s/vagrant/1.9.4/ubuntu/Vagrantfile
## BUG REPORT 

**What happened**:

Refer to open issue #312 , this is a branch issue to fix mix indentation specifically for openebs/k8s/vagrant/1.9.4/ubuntu/Vagrantfile, as part of #hackfest contribution.

**What you expected to happen**:
I will review the file and standardize indentation to 2 spaces

**How to reproduce it (as minimally and precisely as possible)**:
Current file with mix indent: openebs/k8s/vagrant/1.9.4/ubuntu/Vagrantfile

### PR DESCRIPTION
**Pull request by dinukadesilva**
**What this PR does / why we need it**:

Updated openebs/k8s/vagrant/1.9.4/ubuntu/Vagrantfile following Ruby Style Guide indentation best practice:

- Use two spaces per indentation level (aka soft tabs). No hard tabs.
- Align the parameters of a method call if they span more than one line. When aligning parameters is not appropriate due to line-length constraints, single indent for the lines after the first is also acceptable.
- If multiple lines are required to describe the problem, subsequent lines should be indented three spaces after the # (one general plus two for indentation purpose).

**Which issue this PR fixes** 
This fixes #1528

### CODE REVIEW

**Comment by kmova** [comment]
@dinukadesilva - Well written PR. 

Have you tested the changes made to the Vagrantfile?

**Comment by vibhor995** [comment]
@kmova  #1528 
Vagrantfile woking fine.
**output**

 $ vagrant status
Current machine states:

kubemaster-01             running (virtualbox)
kubeminion-01             running (virtualbox)
kubeminion-02             running (virtualbox)

This environment represents multiple VMs. The VMs are all listed
above with their current state. For more information about a specific
VM, run `vagrant status NAME`.

$ kubectl get nodes
NAME            STATUS    ROLES     AGE       VERSION
kubemaster-01   Ready     master    8m        v1.9.4
kubeminion-01   Ready     <none>    4m        v1.9.4
kubeminion-02   Ready     <none>    58s       v1.9.4

**Comment by dinukadesilva** [comment]
I see this is duplicate with https://github.com/openebs/openebs/pull/1515

Shall i close this?

**Comment by ksatchit** [comment]
Yes @dinukadesilva , go ahead!

**Pull request closed without merging**
