### PR TITLE
Translate documentation to Spanish

### LINKED ISSUE #3208: Spanish Translation needed

### PR DESCRIPTION
**Pull request by Akshay-Nagle**
FIXES #3208 Spanish Translation needed

### CODE REVIEW

**Comment by Akshay-Nagle** [comment]
@prateekpandey14 Please review my PR

**Comment by prateekpandey14** [comment]
This changes not required, please pick the issue having `Hacktoberfest` label on it  and make a valid contribution. thanks

**Comment by PedroCisnerosSantana** [comment]
Hello @prateekpandey14 I'm Spanish and there are some translations that are wrong or not the best one, may I translate it?

Thanks :D

**Comment by prateekpandey14** [comment]
Hi @PedroCisnerosSantana thanks for the feedback, if you can please help reviewing this PR that will be great contribution. :D

**Comment by PedroCisnerosSantana** [comment]
Sure @prateekpandey14 the first thing to change is the file name, as for a Spanish translation the filename should be "CONTRIBUTING.es.txt" instead of "CONTRIBUTING.en.txt" as en stands for English, also other files should be. Can start to work on this today, I'm pretty sure can have this done by the end of the day (in Spain)

**Comment by prateekpandey14** [comment]
@PedroCisnerosSantana since @Akshay-Nagle is aleady worked in this one i can't assign you, it will be great if you can help review the PR and make suggestions . :smile: 

Also to contribute more you casn pick the issues having a `Hacktoberfest` or `good-first-issue`

**Comment by PedroCisnerosSantana** [comment]
Most of the document should be changed, you want me to review each mistake?

**Comment by Akshay-Nagle** [comment]
> As we decided to consider the translation PR , re-opening the pull request. @Akshay-Nagle thank you for this PR.
> I have close the other PR #3210 #3209 , can you please merge those changes in this PR itself

@prateekpandey14  I have made the changes you suggested. Please review it

**Comment by kmova** [comment]
@Akshay-Nagle - would it be ok if you can pick up another issue to work on. As this PR seems to contain a lot of changes / commits that shouldn't be part. We can help you out with another good first contribution if you join us on the kubernetes slack ( #openebs-dev ) channel.

**Comment by kmova** [comment]
@PedroCisnerosSantana - would you like to take over this translation and possibly raise a new PR. I am closing this PR as lot of cleanup is required.

**Comment by kmova** [comment]
This PR contains lots of older commits and isn't clean PR.

**Comment by Akshay-Nagle** [comment]
@kmova I apologies for the mess I made in this PR. I`m making a new PR please review that.

**Comment by PedroCisnerosSantana** [comment]
Hello @kmova 
yes, I can take this translation, let me know if you want me to translate it 😄

**Pull request closed without merging**
