### PR TITLE
updating quick-start-with-vim-go.md

### PR DESCRIPTION
**Pull request by anuragsachdeva28**
updating quick-start-with-vim-go.md

Solves issue #1518

### CODE REVIEW

**Comment by kmova** [comment]
@anuragsachdeva28 can you only make the changes to the vim-go file? The other changes have already been merged from your other PR. #1551

**Comment by anuragsachdeva28** [comment]
@kmova my PR #1551 did not contain a sign-off so i decided to close it and create a new PR again.
Was my PR #1551 accepted? Will it be counted as a successful contribution?
This is my first contribution kindly help me.
Thank You.

**Comment by kmova** [comment]
#1551 was not accepted @anuragsachdeva28  but a related one #1552 was accepted. 

In this PR the changes should be only related to vim-go file. You can fix this either: 
- by following git comments to rollback, squash and produce a clean commit with only changes required. It will be cool to learn these git hacks. 
- Or  close this PR and raise a new PR (from a new branch) with only changes required.

**Comment by utkarsh2102** [comment]
Is this PR still being worked up on?
If not, can I take up the issue?

**Comment by utkarsh2102** [comment]
I'm taking up the issue.
CC: @kmova.

**Comment by kmova** [comment]
Thanks @utkarsh2102 - In your PR, can you mark this PR as fixes.

**Comment by utkarsh2102** [comment]
Sure @kmova.
However, the `#` has been already added previously.
But the documentation can be improved in reference to https://github.com/fatih/vim-go-tutorial#quick-setup.
And I'd do the same in that PR marking that as `fixes`, as asked.

**Pull request closed without merging**
