### PR TITLE
fixes #2424, adds support for macos mojave

### LINKED ISSUE #2424: Update Scripts from 0.8.0 to 0.8.1 not working on MacOS due to unsupported command line switch -u for sed.
## Description
update scripts `cstor_pool_upgrade.sh` and `cstor_volume_upgrade.sh` are not compatible with mac os version of sed.

## Expected Behavior
should work

## Current Behavior
```
$ ./cstor_volume_upgrade.sh pvc-XYZ openebs
sed: illegal option -- u
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
sed: illegal option -- u
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
sed: illegal option -- u
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
sed: illegal option -- u
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
sed: illegal option -- u
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
sed: illegal option -- u
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
sed: illegal option -- u
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
sed: illegal option -- u
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
sed: illegal option -- u
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
sed: illegal option -- u
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
Upgrading Target Deployment to 0.8.1
deployment.extensions/pvc-81025020-3dbd-11e9-b408-4c52620a9ebe-target patched
Deployment upgrade strategy set as recreate
error: must specify -p to patch
Failed to patch cstor target deployment pvc-81025020-3dbd-11e9-b408-4c52620a9ebe-target | Exit code: 1
```

## Possible Solution
remove `-u` from sed command.

## Your Environment
* MacOS Mojave 10.14.3

### PR DESCRIPTION
**Pull request by heppstux**
see #2424

### CODE REVIEW

**Comment by ashishranjan738** [comment]
Hi, @heppstux thanks for raising the PR. Can you the sign the DCO please https://github.com/openebs/openebs/pull/2425/checks?check_run_id=71836217.

**Comment by heppstux** [comment]
@ashishranjan738 done.

**Comment by ashishranjan738** [comment]
Also, can you confirm with ubuntu/fedora that it works fine with them as well ?

**Comment by heppstux** [comment]
I could not test explicitly with fedora however Ubuntu (18.04) worked fine.

The -u switch is used to disable buffering, that is useful for piping large files. In the use case here, sed is just used to patch some relatively tiny files - should be fine.

**Comment by ashishranjan738** [comment]
Thanks for the PR @heppstux .

**Comment by heppstux** [comment]
@ashishranjan738 you're welcome, thanks to you all for openebs!

**Pull request merged**
