### PR TITLE
 Signed-off-by: Rajat Garg <rg51096@gmail.com>

### LINKED ISSUE #1498: Typing errors in CONTRIBUTING-TO-DEVELOPER-DOC.md  file
BUG REPORT

**What happened**: There are some tying error in CONTRIBUTING-TO-DEVELOPER-DOC.md file which resides inside the directory contribute. Few periods are missing at the end of the sentences and some unecessary periods are given in the heading section.

**What you expected to happen**: Remove those which are unecessary and add those which are required.

### PR DESCRIPTION
**Pull request by RajatGarg97**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:
This PR  _**'fixes #1498 Typing errors in CONTRIBUTING-TO-DEVELOPER-DOC.md file'**_

### CODE REVIEW

**Comment by RajatGarg97** [comment]
Bug fixed

**Comment by vipulgupta2048** [comment]
@NisantaSahoo @utkarshmani1997  According to my PR #1511, I am already fixing this and it's aimed at fixing and improving the documentation as a whole. I would request to hold off or close this PR, as it would create a bunch of merge conflicts in the work I am currently doing. With no real gains.

**Comment by kmova** [comment]
@RajatGarg97 - Thanks for this PR. Indentation is very important to keep the documents clean and readable. Can I request you to review #1511 to make sure the changes you propose are already incorporated. If not please raise a new PR after #1511 is merged.

**Comment by RajatGarg97** [comment]
Sure that will be great.

**Pull request closed without merging**
