### PR TITLE
Updates slack badge on README with users count

### PR DESCRIPTION
**Pull request by sachinmukherjee**
Signed-off-by: sachinmukherjee <sachinmukherjee29@gmail.com>

**What this PR does / why we need it**:
It updates the slack badge with users count. currently, it is broken

**Which issue this PR fixes**: fixes https://github.com/openebs/openebs/issues/559

### CODE REVIEW

**Comment by utkarshmani1997** [comment]
@sachinmukherjee there are some conflicts in README.md. can you resolve ?

**Comment by sachinmukherjee** [comment]
@do i need to fetch latest changes from upstream and again commit and send PR?

**Comment by prateekpandey14** [comment]
@sachinmukherjee yes, fetch the upstream changes and rebase your branch.
There are alignment issue with slack badge after new changes.
slack-badge

**Comment by sachinmukherjee** [comment]
@prateekpandey14 I will do that Please assign this issue to me

**Comment by kmova** [comment]
@sachinmukherjee  The issue with the slack badge was that a square badge matching other badges was not available. I am closing this PR. It will be great if you can check if the slackin has the fix for a flat-square badge that can give current status.

**Pull request closed without merging**
