### PR TITLE
fix(pool_exporter): remove pool exporter deployment/upgrade templates

### PR DESCRIPTION
**Pull request by utkarshmani1997**
Signed-off-by: Utkarsh Mani Tripathi <utkarsh.tripathi@mayadata.io>
Revert "feat(exporter): add pool-exporter json"
Revert "fix(config): add prefix openebs_io in monitoring"
Revert "feat(exporter): add configuration for pool-exporter"

### CODE REVIEW

**Comment by vishnuitta** [comment]
which is the PR that you are reverting?

**Comment by vishnuitta** [comment]
we need to revert the script as well

**Comment by utkarshmani1997** [comment]
@vishnuitta the code in the script is applied to the deployment which we are patching, so removing the json templates will help. Anyway, I will verify it from my end.

**Comment by vishnuitta** [comment]
this can be kept on hold until we decide how we branch out code for 0.9. Otherwise, changes are good

**Comment by vishnuitta** [comment]
Closing this as pool-exporter got merged into master

**Pull request closed without merging**
