### PR TITLE
Update slack badge with users count

### LINKED ISSUE #559: Update slack badge on openebs/readme.md with users count
Update the slack badge at [README.md](https://github.com/openebs/openebs/blob/master/README.md), to include user information. 

The badge can be changed to : https://openebsslacksignup.herokuapp.com/badge.svg
The link can still remain as : https://openebsslacksignup.herokuapp.com/

### PR DESCRIPTION
**Pull request by ProZsolt**
Fixes #559

### CODE REVIEW

**Comment by prateekpandey14** [comment]
Preview of the Readme.md file, not showing them in single row, can you verify.

**Comment by ProZsolt** [comment]
The problem seems to be with the SVG.
It's in one line but has a huge whitespace under it.
Trying to find a solution.

**Comment by ProZsolt** [comment]
The problem is with [slackin](https://github.com/rauchg/slackin/issues/104)
The badge's width and height are the same.
You coud update slackin, ad that should fix the problem or fok it and patch it with this: https://github.com/rauchg/slackin/pull/103/files, so all badge can be formated to the same.

**Comment by kmova** [comment]
Closing this PR, since there has been no update on this for more than 10 days. Please raise a new PR or re-open when the changes are ready.

**Pull request closed without merging**
