### PR TITLE
Code cleanup/Adding unit test/Fixing flake8 issue

### LINKED ISSUE #137: Add unittests for inventory generation python scripts
Need to add this as the ansible inventory generation scripts are scaling in size

The scripts can be found here : https://github.com/openebs/openebs/tree/master/e2e/ansible/roles/inventory/files

### PR DESCRIPTION
**Pull request by senthilkumar-e**
**What this PR does / why we need it**:
* Code cleanup - 
* Flake8 Fixes
* Unit testing

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
Fixes #137 

**Special notes for your reviewer**:
$ python generate_inventory.py ./machines.in 
Inventory config generated successfully
$ 

$ python test_utils.py 
test_010_replace (__main__.utilsTest) ... ok
----------------------------------------------------------------------
Ran 1 test in 0.000s
OK
[seswaran@seswaran-ld2 test]$ python test_inventory.py 
test_010_validate_inventory (__main__.inventoryTest) ... ok
----------------------------------------------------------------------
Ran 1 test in 0.004s
OK
[seswaran@seswaran-ld2 test]$ python test_validator.py 
test_010_validateip (__main__.validatorTest) ... ok
test_020_validate_input (__main__.validatorTest) ... ok
----------------------------------------------------------------------
Ran 2 tests in 0.000s
OK
$

### CODE REVIEW

**Comment by ksatchit** [comment]
:+1:  :100:

**Comment by senthilkumar-e** [comment]
@ksatchit @kmova Is this PR not qualified for t-shirt :-)  [hackfest](https://openebs.io/hackfest/)

**Comment by umamukkara** [comment]
Probably two :)

**Comment by nitisuryawanshi** [comment]
@senthilkumar-e thanks for contributing to the first edition of OpenEBS Hackfest. We would like to send you some swag as a thank you note for your contribution. Please fill out the following form so that we can send it your way. Many thanks and keep contributing! https://cloudbyte.agilecrm.com/forms/5126296610799616

**Pull request merged**
