### PR TITLE
Fix all the grammatical errors in RELEASE.md

### PR DESCRIPTION
**Pull request by heygroot**
Signed-off-by: heygroot <richa_1217@outlook.com>

### CODE REVIEW

**Comment by KaranSinghBisht** [comment]
Btw why was this pr marked invalid and closed the second fix was infact needed

**Comment by heygroot** [comment]
I guess they don't take documentation fixes as contribution

**Comment by KaranSinghBisht** [comment]
Shouldn't mark it invalid the change is genuine and fixing a typo ...
I mean if they don't just close it, why to add the invalid label

**Comment by heygroot** [comment]
I agree with you, this is not the correct use of invalid tag. @prateekpandey14 if you don't want to merge it, simply close the pr. Btw you will need to fix that typo some day.

**Comment by prateekpandey14** [comment]
@heygroot i think by mistake i added the invalid label on this PR, i was reviewing the other invalid spam PRs,  and added the label on this PR as well.

Anyways changes are good to take , and looks good to me as well.

**Comment by prateekpandey14** [comment]
@heygroot can you raise a PR again, looks like the branch has been deleted from your fork, and i can't reopen the PR

**Comment by heygroot** [comment]
Sure

**Pull request closed without merging**
