### PR TITLE
Updated Readme.md

### PR DESCRIPTION
**Pull request by Shivam7-1**
Changes: Fixes Some typos in Readme.md docs

### CODE REVIEW

**Review by kmova — APPROVED** [review]

**Comment by kmova** [comment]
@Shivam7-1 - thank you for this PR, can you please sign off the commit with your email id as described here:
https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md#sign-your-work

**Comment by Shivam7-1** [comment]
Signed-off-by: Shivam Tiwari shivam.tiwari00021@gmail.com

**Comment by Shivam7-1** [comment]
Signed-off-by: Shivam7-1  shivam.tiwari00021@gmail.com

**Comment by Shivam7-1** [comment]
I want hacktoberfest reward link

**Comment by ShraddhaGeek** [comment]
Is this still open?

**Comment by Shivam7-1** [comment]
It is approved why is it not merged yet

**Comment by Shivam7-1** [comment]
It is approved why is it not merged yet @kmova

**Comment by kmova** [comment]
You can sign up for Hacktoberfest swag from MayaData by entering details here: https://github.com/mayadata-io/swag/issues/new/choose

**Comment by Shivam7-1** [comment]
Is I am win special prize from mayadata like laptop keyboard,NVM drive or Bluetooth
Let me know

**Pull request merged**
