### PR TITLE
Initial commit for openebs iscsi driver, based on FlexVolume.

### PR DESCRIPTION
**Pull request by akashshah26595**
**Status**: 
- openebs-iscsi temporary volume gets created on kubernetes node.
- nginx pod gets deployed, having a mount point.

**Pending issues:**
- Build jq from source and integrate it with the driver.

### CODE REVIEW

**Comment by kmova** [comment]
- Rename the sample yaml file "mount.yaml" as "nginx-openebs-iscsi.yaml" to be more specific. 
- The mount.yaml should contain the following parameters:
   - openebs-api-url ( example value : http://172.28.128.10:5656/latest/
   - size ( 10G) 
   - format (ext4)
   - mount ( mount path name)
   
- In the openebs-iscsi, remove the references to cb~temp
- The flow for the mount command should be as follows:
   * Issue the curl command to the maya-api-server to create the volume with a spec file: 
     ( curl http://172.28.128.10:5656/latest/volume/provision/<volumename> )
     The spec file details are under the https://gihub.com/openebs/mayaserver/
   * The response will contain the iSCSI IP address and iqn details
   * use the iscsiadm to login to iSCSI volume, format and mount it

**Comment by akashshah26595** [comment]
- Made the required changes in yaml file and script.
- Used openebsApiUrl instead of openebs-api-url as parameter key to avoid issues while fetching data in script.

**Comment by AmitKumarDas** [comment]
Have a look at mayaserver's README.

https://github.com/openebs/mayaserver/#mayaservers-rest-apis

Plugin will need to call multiple APIs to learn about the IQN info.

If the provisioning is in pending status, then Mayaserver will not publish the portal & IQN info.

**Comment by kmova** [comment]
Replace the debug prints ( echo to temp file) to using log()

**Comment by AmitKumarDas** [comment]
Please introduce the shell linting tool that can check various shell related issues.

https://github.com/koalaman/shellcheck

It will be worthwhile to introduce `bats` as unit testing for this script.

**Pull request merged**
