### PR TITLE
delete unused line

### LINKED ISSUE #2193: Add proper comment and fix linting issue
## FEATURE REQUEST?

**What happened**:

-  Add comments and fix linting issue

https://github.com/openebs/openebs/blob/master/e2e/ansible/files/updater.py

**Anything else we need to know?**:

### PR DESCRIPTION
**Pull request by IgnasA**
Signed-off-by: Ignas Ausiejus <ausiejus.ignas@gmail.com>

**What this PR does / why we need it**: Simply found some code that was not used

**Which issue this PR fixes**: fixes #2193

### CODE REVIEW

**Comment by princerachit** [comment]
please fix dco sign and update your PR

**Comment by IgnasA** [comment]
@princerachit I think something is wrong with DCO sign off for the whole project.

**Comment by Akash4927** [comment]
Hi @IgnasA, you have 3 commits and you signed only one of them. You have to sign all the commits.

**Comment by gprasath** [comment]
e2e has been moved to litmus.

**Pull request closed without merging**
