### PR TITLE
updated CONTRIBUTING.md

### LINKED ISSUE #1496: Update CONTRIBUTING.md
## FEATURE REQUEST
In CONTRIBUTING.md instead of "Open Source" ,it is written like "OpenSource".

**What happened**:
In CONTRIBUTING.md ,"Open Source" is written like "OpenSource".

**What you expected to happen**:
It should be like "Open Source".
**How to reproduce it (as minimally and precisely as possible)**:
Just updation  is required.

### PR DESCRIPTION
**Pull request by Rupeshiya**
Signed-off-by: Rupeshiya <rupeshiya@gmail.com>
**What this PR does / why we need it**:
This PR updated CONTRIBUTING.md
It adds a missing space between Open Source in CONTRIBUTING.md file.
Earlier there was no space and it was written like this OpenSource.
Now in this PR, it looks like this Open Source.
**Which issue this PR fixes** 
This PR fixes #1496

### CODE REVIEW

**Comment by Rupeshiya** [comment]
@sachinmukherjee  I am modifying it  in my forked repositery and after than creating PR directly to openEBS.
What's worng in this?

**Comment by sachinmukherjee** [comment]
@Rupeshiya I was facing the same issue when i was editing using Github. After that I have started editing using git and the submit a PR. Try to use git.

**Comment by Rupeshiya** [comment]
@sachinmukherjee  How to edit file and sending PR using git?

**Comment by vipulgupta2048** [comment]
@NisantaSahoo @utkarshmani1997  According to my PR #1511, I am already fixing this and it's aimed at fixing and improving the documentation as a whole. I would request to hold off or close this PR, as it would create a bunch of merge conflicts in the work I am currently doing. With no real gains.

**Comment by kmova** [comment]
I agree with @vipulgupta2048. 

@Rupeshiya @sachinmukherjee - can you review the PR #1511 to see that your changes are incorporated.

**Pull request closed without merging**
