### PR TITLE
Changed link in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by vinayak42**
Signed-off-by: Vinayak <vinayak17122@iiitd.ac.in>

**What this PR does / why we need it**:
Since most of us are English speakers and readers, I changed the link of git book - aliases chapter to the English language one.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:
I hope the link isn't meant for Turkish readers/speakers

### CODE REVIEW

**Comment by princerachit** [comment]
Please fix dco signoff

**Comment by vinayak42** [comment]
@princerachit I missed signing off the commit. How do I fix that? Do I need to remove this commit and push another one with the sign-off?

**Comment by kmova** [comment]
@vinayak42 you can either ammend your commit message or mention the email id in the PR description.

**Comment by vinayak42** [comment]
@kmova I have mentioned email id in PR description, still, it is showing that sign-off is missing. Also, I am not being able to amend my commit message.

**Comment by vinayak42** [comment]
Email ID: vinayak17122@iiitd.ac.in

**Comment by NisantaSahoo** [comment]
Hi @vinayak42 . I have sent you a mail regarding Hacktoberfest Swags. Can you please check your inbox and fill up the form

**Comment by vinayak42** [comment]
Filled it up. Thanks!

**Pull request merged**
