### PR TITLE
Adding high level steps to the existing playbooks

### PR DESCRIPTION
**Pull request by gprasath**
Signed-off-by: gprasath <giridhara.prasad@cloudbyte.com>

Added steps at the top of each playbook yamls.

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by ksatchit** [comment]
Thanks for doing this @gprasath !! If possible, could you also rename the tasks to correspond to a step (steps that are spread across multiple tasks can be identified as, say, 1a, 1b, 2a, 2b etc..,) . This will help users/contributors that are viewing/debugging it.

**Comment by ksatchit** [comment]
Can we have a snippet of any one task executed post numbering? Or probably a partial o/p with `--check` flag. Just curious to know if the ")" has any impact :)

**Comment by gprasath** [comment]
@ksatchit it gets printed as it is. Will paste the snippet here shortly

**Comment by gprasath** [comment]
@ksatchit , As requested pasting the snippet of a task output.
```
TASK [4) Deploy percona mysql pod] *************************************************************************************************************************************
task path: /home/giri/new_fork/openebs/e2e/ansible/playbooks/hyperconverged/test-k8s-percona-mysql-pod/k8s-percona-pod.yml:81
changed: [localhost -> None] => {"changed": true, "cmd": "source ~/.profile; kubectl create -f demo-percona-mysql-pvc.yaml", "delta": "0:00:01.179809", "end": "2018-05-07 05:43:12.361670", "rc": 0, "start": "2018-05-07 05:43:11.181861", "stderr": "", "stderr_lines": [], "stdout": "pod \"percona\" created\npersistentvolumeclaim \"percona-db-claim\" created", "stdout_lines": ["pod \"percona\" created", "persistentvolumeclaim \"percona-db-claim\" created"]}
```

**Pull request merged**
