### PR TITLE
Allow configuration of replicas/affinity and refactor to follow common helm patterns

### PR DESCRIPTION
**Pull request by rtluckie**
- add ability to configure apiserver and provisioner replica count and
affinity
- allow configuration of ports via values
- refactor labels
- refactor to follow observed patterns in stable charts and helm create

### CODE REVIEW

**Comment by kmova** [comment]
Very useful changes @rtluckie. Thank you!

Btw, should we mention a minimum version of helm that is required to support these changes?

**Comment by muratkars** [comment]
Installation using Helm charts completes without an issue, whoever PVC gets stuck and can't deploy demo workloads after. I believe this is due to refactoring of provisioner and maya-apiserver names ({releasename}-openebs-maya-apiserver). Provisioner may have hardcoded name dependency for openebs-maya-apiserver service

**Comment by rtluckie** [comment]
@muratkars I came across [this](https://github.com/kubernetes-incubator/external-storage/blob/master/openebs/pkg/v1/maya_api.go#L65) hardcoded name dependency. Are you aware of any others?

**Comment by AmitKumarDas** [comment]
@rtluckie Not sure. However, this seems to be the only hardcoding.

**Comment by rtluckie** [comment]
@muratkars @AmitKumarDas Found and fixed issue (label/selector mismatch) and tested with crunchy-postgres demo workload. Changes seem to be working now.

**Comment by prateekpandey14** [comment]
Thanks @rtluckie.

**Comment by kmova** [comment]
Thanks @rtluckie 

I was trying to reproduce the issue by taking your changes and it actually worked! turns out you fixed the issue before i could reproduce it!

```
kiran_mova@kmova-dev:~/go/src/github.com/rtluckie/openebs/k8s/charts/openebs$ kubectl get pods
NAME                                              READY     STATUS    RESTARTS   AGE
openebs-openebs-grafana-84694dfd69-7wqc6          1/1       Running   0          16s
openebs-openebs-maya-apiserver-867f6dcd58-4kt7n   1/1       Running   0          16s
openebs-openebs-maya-apiserver-867f6dcd58-vx47t   1/1       Running   0          16s
openebs-openebs-prometheus-7c489b8bbf-wgz7f       1/1       Running   0          16s
openebs-openebs-provisioner-5ccd865584-577qb      1/1       Running   0          16s
openebs-openebs-provisioner-5ccd865584-tv7bc      1/1       Running   0          16s
kiran_mova@kmova-dev:~/go/src/github.com/rtluckie/openebs/k8s/charts/openebs$ kubectl get service
NAME                                 TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
kubernetes                           ClusterIP   10.39.240.1     <none>        443/TCP          28m
maya-apiserver-service               ClusterIP   10.39.255.155   <none>        5656/TCP         33s
openebs-openebs-grafana              NodePort    10.39.241.122   <none>        3000:32515/TCP   33s
openebs-openebs-prometheus-service   NodePort    10.39.240.71    <none>        80:32514/TCP     32s
kiran_mova@kmova-dev:~/go/src/github.com/rtluckie/openebs/k8s/charts/openebs$ 
kiran_mova@kmova-dev:~/go/src/github.com/rtluckie/openebs/k8s/charts/openebs$ 
kiran_mova@kmova-dev:~/go/src/github.com/rtluckie/openebs/k8s/charts/openebs$ 
kiran_mova@kmova-dev:~/go/src/github.com/rtluckie/openebs/k8s/charts/openebs$ kubectl get sc
NAME                 PROVISIONER
openebs-cassandra    openebs.io/provisioner-iscsi
openebs-es-data-sc   openebs.io/provisioner-iscsi
openebs-jupyter      openebs.io/provisioner-iscsi
openebs-kafka        openebs.io/provisioner-iscsi
openebs-mongodb      openebs.io/provisioner-iscsi
openebs-percona      openebs.io/provisioner-iscsi
openebs-redis        openebs.io/provisioner-iscsi
openebs-standalone   openebs.io/provisioner-iscsi
openebs-standard     openebs.io/provisioner-iscsi
openebs-zk           openebs.io/provisioner-iscsi
standard (default)   kubernetes.io/gce-pd
kiran_mova@kmova-dev:~/go/src/github.com/rtluckie/openebs/k8s/charts/openebs$ 


kiran_mova@kmova-dev:~/go/src/github.com/rtluckie/openebs/k8s/demo/percona$ kubectl get pods
NAME                                                             READY     STATUS    RESTARTS   AGE
openebs-openebs-grafana-84694dfd69-7wqc6                         1/1       Running   0          3m
openebs-openebs-maya-apiserver-867f6dcd58-4kt7n                  1/1       Running   0          3m
openebs-openebs-maya-apiserver-867f6dcd58-vx47t                  1/1       Running   0          3m
openebs-openebs-prometheus-7c489b8bbf-wgz7f                      1/1       Running   0          3m
openebs-openebs-provisioner-5ccd865584-577qb                     1/1       Running   0          3m
openebs-openebs-provisioner-5ccd865584-tv7bc                     1/1       Running   0          3m
percona                                                          1/1       Running   0          40s
pvc-a6a6b694-fba6-11e7-b716-42010a800347-ctrl-846cdd47b8-pzppn   2/2       Running   0          40s
pvc-a6a6b694-fba6-11e7-b716-42010a800347-rep-7786d6957c-fsp97    1/1       Running   0          39s
pvc-a6a6b694-fba6-11e7-b716-42010a800347-rep-7786d6957c-ldzn8    1/1       Running   0          39s
kiran_mova@kmova-dev:~/go/src/github.com/rtluckie/openebs/k8s/demo/percona$ kubectl get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS    CLAIM                     STORAGECLASS      REASON    AGE
pvc-a6a6b694-fba6-11e7-b716-42010a800347   5G         RWO            Delete           Bound     default/demo-vol1-claim   openebs-percona             1m
kiran_mova@kmova-dev:~/go/src/github.com/rtluckie/openebs/k8s/demo/percona$ kubectl get pvc
NAME              STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
demo-vol1-claim   Bound     pvc-a6a6b694-fba6-11e7-b716-42010a800347   5G         RWO            openebs-percona   1m
kiran_mova@kmova-dev:~/go/src/github.com/rtluckie/openebs/k8s/demo/percona$
```

**Comment by muratkars** [comment]
Tested both on IBM Cloud Private and StackPointCloud and deployed postgres. Patch works. Thanks @rtluckie 

ubuntu@ip-172-23-1-99:~/openebs/k8s/demo/crunchy-postgres$ kubectl get pods
NAME                                                            READY     STATUS    RESTARTS   AGE
openebs-shrill-union-openebs-grafana-5dc4fcc5b7-hkshx           1/1       Running   0          12m
openebs-shrill-union-openebs-maya-apiserver-78fbd996df-966tn    1/1       Running   0          12m
openebs-shrill-union-openebs-maya-apiserver-78fbd996df-v9g47    1/1       Running   0          12m
openebs-shrill-union-openebs-prometheus-7fb5f59b9c-n42ql        1/1       Running   0          12m
openebs-shrill-union-openebs-provisioner-7d7bf8645c-qtr9v       1/1       Running   0          12m
openebs-shrill-union-openebs-provisioner-7d7bf8645c-tdw54       1/1       Running   0          12m
pgset-0                                                         1/1       Running   0          5m
pgset-1                                                         1/1       Running   0          4m
pvc-9cf1ab5f-fbaa-11e7-ad38-062f7d9b7f40-ctrl-5b5cdf6b-pnsbs    2/2       Running   0          5m
pvc-9cf1ab5f-fbaa-11e7-ad38-062f7d9b7f40-rep-7c77f6bfc8-mbwdr   1/1       Running   0          5m
pvc-9cf1ab5f-fbaa-11e7-ad38-062f7d9b7f40-rep-7c77f6bfc8-rnkb7   1/1       Running   0          5m
pvc-d2679db2-fbaa-11e7-ad38-062f7d9b7f40-ctrl-d69bb7b67-224wn   2/2       Running   0          4m
pvc-d2679db2-fbaa-11e7-ad38-062f7d9b7f40-rep-85d67b5d78-5pl7l   1/1       Running   0          4m
pvc-d2679db2-fbaa-11e7-ad38-062f7d9b7f40-rep-85d67b5d78-6q4xk   1/1       Running   0          4m
ubuntu@ip-172-23-1-99:~/openebs/k8s/demo/crunchy-postgres$ kubectl get service
NAME                                                TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)             AGE
kubernetes                                          ClusterIP   10.3.0.1     <none>        443/TCP             23h
maya-apiserver-service                              ClusterIP   10.3.0.74    <none>        5656/TCP            13m
openebs-shrill-union-openebs-grafana                NodePort    10.3.0.235   <none>        3000:32515/TCP      13m
openebs-shrill-union-openebs-prometheus-service     NodePort    10.3.0.253   <none>        80:32514/TCP        13m
pgset                                               ClusterIP   None         <none>        5432/TCP            6m
pgset-primary                                       ClusterIP   10.3.0.94    <none>        5432/TCP            6m
pgset-replica                                       ClusterIP   10.3.0.159   <none>        5432/TCP            6m
pvc-9cf1ab5f-fbaa-11e7-ad38-062f7d9b7f40-ctrl-svc   ClusterIP   10.3.0.17    <none>        3260/TCP,9501/TCP   6m
pvc-d2679db2-fbaa-11e7-ad38-062f7d9b7f40-ctrl-svc   ClusterIP   10.3.0.239   <none>        3260/TCP,9501/TCP   5m

**Pull request merged**
