### PR TITLE
Fixes typing errors in CONTRIBUTING-TO-DEVELOPER-DOC.md file

### PR DESCRIPTION
**Pull request by sachinmukherjee**
Signed-off-by: sachinmukherjee sachinmukherjee29@gmail.com

**What this PR does / why we need it**: 
- It fixes some typing erros in CONTRIBUTING-TO-DEVELOPER-DOC.md file which resides inside directory contribute.
- Some periods(.) are missing that are added in this PR.
- Some periods(.) are unecessary that are removed in this PR.

**Which issue this PR fixes**: fixes https://github.com/openebs/openebs/issues/1498

### CODE REVIEW

**Comment by sachinmukherjee** [comment]
@utkarshmani1997 Please review.

**Comment by utkarshmani1997** [comment]
@sachinmukherjee can you please squash and merge your commits into one commit ?

**Comment by sachinmukherjee** [comment]
@utkarshmani1997  can you help me how to do that. I'm facing difficulty in doing that.

**Comment by utkarshmani1997** [comment]
@sachinmukherjee sure! can we discuss on slack ?

**Comment by sachinmukherjee** [comment]
@utkarshmani1997 Please review.

**Comment by vipulgupta2048** [comment]
@NisantaSahoo @utkarshmani1997  According to my PR #1511, I am already fixing this and it's aimed at fixing and improving the documentation as a whole. I would request to hold off or close this PR, as it would create a bunch of merge conflicts in the work I am currently doing. With no real gains.

**Comment by kmova** [comment]
@sachinmukherjee - Could you please review #1511 to see if your changes are already incorporated. If not, can you please raise a new PR with your changes once #1511 is merged. ( cc: @vipulgupta2048 )

**Pull request closed without merging**
