### PR TITLE
Add the resiliency testcase for periodic single volume replica failures 

### PR DESCRIPTION
**Pull request by yudaykiran**
**What this PR does / why we need it**:
- Add the resiliency usecase for single replica.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes # (Partial Fix for #1048)

**Special notes for your reviewer**:
Signed-off-by: yudaykiran <udaykiran.y@gmail.com>

### CODE REVIEW

**Comment by kmova** [comment]
@yudaykiran can you describe the approach followed here in the PR description?

**Comment by ksatchit** [comment]
Note: Also refer #1383 for the bug seen while performing this test

**Comment by yudaykiran** [comment]
When running OpenEBS with the number of volume replicas set to 1, the following behavior is expected of a pod when it is restarted:
- If the volume pod is restarted and is respawned on the same node it was running earlier, it should be able to start itself in RW mode rather than RO mode as quorum rules do not apply for this use case.

The ansible-playbook does the following:
1. Use Percona with load-gen to store data into the volume.
2. Identify the node in which the volume pod was created.
3. Cordon all other nodes, so that the volume pod gets scheduled on the same node if restarted.
4. Run chaos-kube for fault injection.(Pod Kills)
5. Check the status of the Percona Pod after the volume pod restart.
6. The Percona pod will be in running state if the volume pod started with the RW state and also the hostdir is in RW state, the test passes.
7. The Percona pod will be in CrashloopBackoff if the volume pod started with the RO or RW and the hostdir is in RO state, causing the volume to be inaccessible to write, the test failes.

**Comment by kmova** [comment]
Shouldn't the replica always be restarted on the same node without cardoning?

**Comment by kmova** [comment]
I got it. So this is to simulate the case where restart of the pod within the same node will not cause IO errors. The cases of ensuring that replica pods will not get rescheduled to a new node will be covered in a different test case.

**Pull request merged**
