### PR TITLE
Create pvc-standard-cstor-disk.yaml

### PR DESCRIPTION
**Pull request by ranjithwingrider**
Signed-off-by: ranjith.raveendran@openebs.io

**What this PR does / why we need it**:
New sample yaml for consuming cstor pool created using external disk. We are proving sample SPC with storage class in the doc but we dont have pvc to consume this Pool.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:
So that all sample pvc yamls should be under same location

### CODE REVIEW

**Comment by kmova** [comment]
@ranjithwingrider - Can you point me to the doc location where this file will be referred? wondering if the docs itself can contain this example.

**Comment by ranjithwingrider** [comment]
@kmova It is the replacement of step 8 in https://docs.openebs.io/docs/next/deploycstor.html

**Comment by ranjithwingrider** [comment]
I feel all samples will be under one location and  so that user can select the needed yaml as per the naming convention if he is not following doc also. Also existing one which is being used currently has been modified.

**Comment by kmova** [comment]
cool. Can you put it with other sample yamls in `k8s/sample-pv-yamls`

**Comment by ranjithwingrider** [comment]
It's Done.

**Pull request merged**
