### PR TITLE
Added Hindi translation

### PR DESCRIPTION
**Pull request by iamrajiv**
Fixes: #3163

### CODE REVIEW

**Comment by prateekpandey14** [comment]
@iamrajiv . thank you for this PR, can you please sign off the commit with your email id as described here:

https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md#sign-your-work

**Comment by prateekpandey14** [comment]
@iamrajiv , since there are 2 commits, out of which one is signed,  better to squash the commits.

**Comment by ShivaniThevar** [comment]
Hey @prateekpandey14 ,

I suppose this issue was resolved. If not, I would like to contribute.

**Comment by iamrajiv** [comment]
@prateekpandey14 Done with the requested changes. Thanks for help!

**Comment by kmova** [comment]
Hi @iamrajiv, we modified the links to the translated files a bit in the REAMDE.md for better experience. As part of this PR, can you update and resolve conflicts the README.md, add links in the ./translations/readme.md and also update the hindi translated file to have the link to translations on the top. Please check the gujrati translation file for reference.

**Comment by iamrajiv** [comment]
@kmova @prateekpandey14 Done with requested changes.

**Review by kmova — APPROVED** [review]

**Comment by kmova** [comment]
Thank you @iamrajiv. You can sign up for Hacktoberfest swag from MayaData by entering details here: https://github.com/mayadata-io/swag/issues/new/choose

**Pull request merged**
