### PR TITLE
Added Nepali Language

### PR DESCRIPTION
**Pull request by AshishMhrzn10**
I added Nepali language. Added CONTRIBUTING.np.md and README.np.md. Please check it..

### CODE REVIEW

**Comment by AshishMhrzn10** [comment]
@kmova and @ItsJulian , please can I get any review on this PR ??

**Comment by prateekpandey14** [comment]
This changes not required, please pick the issue having `Hacktoberfest` label on it  and make a valid contribution. thanks

**Comment by prateekpandey14** [comment]
As we decided to consider the translation PR , re-opening the pull request. @AshishMhrzn10  thank you for this PR.

**Comment by AshishMhrzn10** [comment]
@prateekpandey14  Thank u brother, much more appreciated. Please can I get the review of my PR and get some reply. That would help a lot.

**Comment by kmova** [comment]
Hi @AshishMhrzn10 - we modified the links to the translated files a bit in the REAMDE.md for better experience. As part of this PR, can you update and resolve conflicts the README.md, add links in the ./translations/readme.md and also update the hindi translated file to have the link to translations on the top. Please check the gujrati translation file for reference.

**Comment by AshishMhrzn10** [comment]
@kmova Please have a look now. If there is any more update required, then I would be happy to take it.

**Comment by kmova** [comment]
@AshishMhrzn10 - Can you make sure the only changes in the PR are to add CONTRIBUTING.np.md and README.np.md. 

This PR deletes an existing file, which should not be the case.

**Comment by AshishMhrzn10** [comment]
@kmova  does this solve the issue? README.de.md keeps on showing the change, so I tried to keep it same as in the openebs directory.  Any solution to this I can make??

**Comment by AshishMhrzn10** [comment]
@kmova please can u review ?? If this doesn't work than I can create a new PR with only CONTRIBUTING.np.md and README.np.md .

**Comment by kmova** [comment]
@AshishMhrzn10 can you possibly raise a new PR with just the changes to the nepali translation?

**Comment by AshishMhrzn10** [comment]
ok sure.

**Comment by AshishMhrzn10** [comment]
Please check the PR #3290

**Pull request closed without merging**
