### PR TITLE
chore(doc): updating community meeting details

### PR DESCRIPTION
**Pull request by pawanpraka1**
Signed-off-by: Pawan <pawan@mayadata.io>

### CODE REVIEW

**Review by GlennBullingham — COMMENTED** [review]
Did we discuss moving the time of the meeting to something more compatible with Europe / US (Eastern)?  I recall the decision to limit the cadence to bi-weekly but not exactly what we concluded with regarding to timing.

**Comment by pawanpraka1** [comment]
@GlennBullingham we have concluded on timing also in that meeting. It is there in the MOM.

**Review by GlennBullingham — APPROVED** [review]

**Review by avishnu — APPROVED** [review]
LGTM

**Comment by pawanpraka1** [comment]
@kmova Please take a look at this PR.

**Pull request merged**
