### PR TITLE
Fixed indentation in k8s/vagrant/1.8.2/Vagrantfile

### LINKED ISSUE #1512: Is this a BUG REPORT or FEATURE REQUEST?
## BUG REPORT
 
 BUG REPORT

**What happened**:

With respect to Issue #312 , the indentation in openebs/k8s/lib/vagrant/test/k8s/1.8.2/Vagrantfile is mixed and it should be standardized.

**What you expected to happen**:

Standardize the indentation.

**How to reproduce it (as minimally and precisely as possible)**:

openebs/k8s/lib/vagrant/test/k8s/1.8.2/Vagrantfile has mixed indentation and its not standardized.

### PR DESCRIPTION
**Pull request by palash16**
Signed-off-by: palash16 <konnectpalash@gmail.com>

**What this PR does / why we need it**:

1. Updates /openebs/k8s/lib/vagrant/test/k8s/1.8.2/Vagrantfile . Use two spaces per indentation level (aka soft tabs)
2. If multiple lines are required to describe the problem, subsequent lines should be indented three spaces after the # (one general plus two for indentation purpose).

**Which issue this PR fixes** : fixes #1512 (partial fix  for #312 )

**Special notes for your reviewer**:

Please review and provide further suggestions if any. Thanks

### CODE REVIEW

**Comment by kmova** [comment]
Hi @palash16 - after making the changes, did you try to run this Vagrantfile?

**Comment by palash16** [comment]
@kmova yes it was working fine

**Comment by nsathyaseelan** [comment]
@kmova  This Vagrantfile is LGTM
Able to run and bring up the vagarnt vms.

```
devops@devops-virtual-machine:~/k8s-demo/pr14$ vagrant status
==> vagrant: A new version of Vagrant is available: 2.1.1!
==> vagrant: To upgrade visit: https://www.vagrantup.com/downloads.html

Current machine states:

kubemaster-01             running (virtualbox)
kubeminion-01             running (virtualbox)
kubeminion-02             running (virtualbox)

This environment represents multiple VMs. The VMs are all listed
above with their current state. For more information about a specific
VM, run `vagrant status NAME`.
```

**Comment by NisantaSahoo** [comment]
Congratulations for your PR getting merged! Thanks for taking part in OpenEBS Hackfest.
Fill up the doc form to get the Hackfest T-Shirt and Swags
https://docs.google.com/spreadsheets/d/1TZYIdERnD72YPeUsdS5hDfI6xgXXCax4-DHpXh-o6r0/edit?usp=sharing
Looking for some more awesome contributions from you and win exciting prizes

**Pull request merged**
