### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by Rupeshiya**
**What this PR does / why we need it**:
This PR correct the typing error of CONTRIBUTING.md.
Instead of "Open Source" it is written like "OpenSource" in CONTRIBUTING.md.
**Which issue this PR fixes** 
It fixes issue #1496

### CODE REVIEW

**Comment by vipulgupta2048** [comment]
If you ask me a more appropriate version would be open-source. Also, the sign off is missing. I recommend using the command `git commit -s -m "Whatever git message"` to include a sign-off in your commits to pass the checks.

**Comment by Rupeshiya** [comment]
@vipulgupta2048  How can I make it correct now since I have sent PR. ?

**Comment by Rupeshiya** [comment]
@vipulgupta2048  Since I have seen that you have send many PRs in openebs, so can you send me the whole command snapshot on slack  means what to do after forking repo because I have tried to do this from last two days but cannot do.

**Comment by vipulgupta2048** [comment]
@NisantaSahoo @utkarshmani1997  According to my PR #1511, I am already fixing this and it's aimed at fixing and improving the documentation as a whole. I would request to hold off or close this PR, as it would create a bunch of merge conflicts in the work I am currently doing. With no real gains.

**Comment by kmova** [comment]
@Rupeshiya Please review if your changes are incorporated by #1511. Also DCO commit is a must for the PRs. The sign-off should be in the commit messages.

**Pull request closed without merging**
