### PR TITLE
Vagrant kube upgrade to 1.7.5 #222

### LINKED ISSUE #222: Update to the latest Kubernetes
This is an enhancement request to bump the version of Kubernetes to the latest (1.7.5 at the time of this writing).

Kind regards.

### PR DESCRIPTION
**Pull request by kmova**
Updated the configuration and spec files for Kubernetes 1.7.5

This PR fixes #222 
This PR also makes the initial commits for automating the process of creating a kubernetes box.

### CODE REVIEW

**Comment by yudaykiran** [comment]
Is patching of kube-proxy not required any more? We run it in --proxy-mode=userspace. What mode will it be using now?

**Comment by kmova** [comment]
It is not required since kube-proxy and weave are running in the same name space.

**Comment by yudaykiran** [comment]
It would be good if a sample output of the kubectl commands are put so that we know it works.

**Comment by kmova** [comment]
After launching cluster. 

```
kiran@kmaya:~/github/kmova/openebs/k8s/vagrant/1.7.5$ vagrant status
Current machine states:

kubemaster-01             running (virtualbox)
kubeminion-01             running (virtualbox)
kubeminion-02             running (virtualbox)

This environment represents multiple VMs. The VMs are all listed
above with their current state. For more information about a specific
VM, run `vagrant status NAME`.
kiran@kmaya:~/github/kmova/openebs/k8s/vagrant/1.7.5$ vagrant ssh kubemaster-01
Welcome to Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-64-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud

132 packages can be updated.
59 updates are security updates.

Last login: Mon Sep 11 06:38:04 2017 from 10.0.2.2
ubuntu@kubemaster-01:~$ kubectl get pods --all-namespaces
NAMESPACE     NAME                                    READY     STATUS    RESTARTS   AGE
kube-system   etcd-kubemaster-01                      1/1       Running   0          1h
kube-system   kube-apiserver-kubemaster-01            1/1       Running   0          1h
kube-system   kube-controller-manager-kubemaster-01   1/1       Running   1          1h
kube-system   kube-dns-2425271678-vlnw0               3/3       Running   0          1h
kube-system   kube-proxy-n7flt                        1/1       Running   0          1h
kube-system   kube-proxy-q4kw8                        1/1       Running   0          1h
kube-system   kube-proxy-stlz7                        1/1       Running   0          1h
kube-system   kube-scheduler-kubemaster-01            1/1       Running   1          1h
kube-system   kubernetes-dashboard-3313488171-0cmbj   1/1       Running   0          1h
kube-system   weave-net-0ztld                         2/2       Running   0          1h
kube-system   weave-net-5j9g7                         2/2       Running   0          1h
kube-system   weave-net-t72df                         2/2       Running   0          1h
ubuntu@kubemaster-01:~$ 
```

**Comment by kmova** [comment]
Copied and applied the openebs-operator.yaml and openebs-storageclasses.yaml
```
ubuntu@kubemaster-01:~$ kubectl apply -f /vagrant/openebs-operator.yaml 
serviceaccount "openebs-maya-operator" created
clusterrole "openebs-maya-operator" created
clusterrolebinding "openebs-maya-operator" created
deployment "maya-apiserver" created
service "maya-apiserver-service" created
deployment "openebs-provisioner" created
ubuntu@kubemaster-01:~$ kubectl apply -f /vagrant/openebs-storageclasses.yaml 
storageclass "openebs-basic" created
storageclass "openebs-percona" created
storageclass "openebs-jupyter" created
ubuntu@kubemaster-01:~$ 
ubuntu@kubemaster-01:~$ kubectl get pods
NAME                                   READY     STATUS    RESTARTS   AGE
maya-apiserver-546443015-cwk9q         1/1       Running   0          1m
openebs-provisioner-3862123968-q98nx   1/1       Running   0          1m
ubuntu@kubemaster-01:~$ 
```

**Comment by yudaykiran** [comment]
LGTM

**Comment by kmova** [comment]
Creating fio pod:

```
ubuntu@kubemaster-01:~$ cd demo/
ubuntu@kubemaster-01:~/demo$ ls -lrt
total 8
-rw-r--r-- 1 root root 635 Sep 11 04:32 demo-vdbench-openebs.yaml
-rw-r--r-- 1 root root 645 Sep 11 04:32 demo-fio-openebs.yaml
ubuntu@kubemaster-01:~/demo$ kubectl apply -f demo-fio-openebs.yaml 
pod "tests-fio" created
persistentvolumeclaim "demo-vol1-claim" created
ubuntu@kubemaster-01:~/demo$ 
ubuntu@kubemaster-01:~/demo$ kubectl get pv,pvc
NAME                                          CAPACITY   ACCESSMODES   RECLAIMPOLICY   STATUS    CLAIM                     STORAGECLASS    REASON    AGE
pv/pvc-cb7efa5a-96c1-11e7-ae42-021c6f7dbe9d   5G         RWO           Delete          Bound     default/demo-vol1-claim   openebs-basic             1m

NAME                  STATUS    VOLUME                                     CAPACITY   ACCESSMODES   STORAGECLASS    AGE
pvc/demo-vol1-claim   Bound     pvc-cb7efa5a-96c1-11e7-ae42-021c6f7dbe9d   5G         RWO           openebs-basic   1m
ubuntu@kubemaster-01:~/demo$ 

ubuntu@kubemaster-01:~/demo$ kubectl get pods
NAME                                                            READY     STATUS    RESTARTS   AGE
maya-apiserver-546443015-cwk9q                                  1/1       Running   0          5m
openebs-provisioner-3862123968-q98nx                            1/1       Running   0          5m
pvc-cb7efa5a-96c1-11e7-ae42-021c6f7dbe9d-ctrl-846411756-bl1rn   1/1       Running   0          3m
pvc-cb7efa5a-96c1-11e7-ae42-021c6f7dbe9d-rep-1709458107-gqr8s   1/1       Running   0          3m
pvc-cb7efa5a-96c1-11e7-ae42-021c6f7dbe9d-rep-1709458107-tt0ps   1/1       Running   0          3m
tests-fio                                                       1/1       Running   0          3m
ubuntu@kubemaster-01:~/demo$ 

```

**Comment by kmova** [comment]
Installed kubectl on my ubuntu host and used kubectl proxy, to access the UI:
```
vagrant ssh kubemaster-01 -c "cat ~/.kube/config" > ~/.kube/local-config
kubectl --kubeconfig ~/.kube/local-config proxy
>Starting to serve on 127.0.0.1:8001
```
Listing the Pods from UI

image

Accessing the maya-cli from the UI and running the stats command
image

**Pull request merged**
