### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by vyaspranjal33**
added License badge and https in site URL

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by vyaspranjal33** [comment]
@utkarshmani1997 please consider this PR ,commits is verified by github

**Comment by vyaspranjal33** [comment]
@utkarshmani1997  please let me know how to sign pushed commit

**Comment by Akash4927** [comment]
hi @vyaspranjal33 you can sign your commit using `git commit -s --amend` and you can push it using `git push origin master -f`

**Comment by Akash4927** [comment]
@vyaspranjal33 Can you change the commit message and remove the Signed-off line from Heading.
Use the above command again to do the same.

**Pull request merged**
