### PR TITLE
Fix for issue #220. Made the python code PEP008 compliant.

### PR DESCRIPTION
**Pull request by Endi1**
**What this PR does / why we need it**:
Fixes issue #220. Makes all the python code PEP008 compliant.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
#220

### CODE REVIEW

**Comment by kmova** [comment]
@Endi1 - thanks for the PR. The changes look good!

Btw, what tools/command did you use to list the non-compliant code?

**Comment by Endi1** [comment]
I used Flake8 and Spacemacs with the Python layer with a Flake8 minor mode.

**Comment by kmova** [comment]
Thanks @Endi1 

Can you also check the following file please : *e2e/ansible/plugins/callback/openebs.py* ?

**Comment by Endi1** [comment]
Ahh must have missed that. I used `find . | grep *.py` to find the files
and didn't get that one as a result.

**Comment by kmova** [comment]
@Endi1 - will you be submitting another commit to the existing PR? or
Should I create a new issue for fixing the openebs.py file, and merge the changes of this PR?

**Comment by Endi1** [comment]
I'll be submitting another commit to this PR a bit later today.

**Comment by nitisuryawanshi** [comment]
@Endi1 Thank you so much for your PR contribution! We would like to mention you in our tweets, thanking you for your contribution. Can you please send me your twitter handle on this mail ID <niti.suryawanshi@openebs.io> ?

**Pull request merged**
