### PR TITLE
Fix spelling

### PR DESCRIPTION
**Pull request by hugovk**
## Description

Fix some spelling.

## Motivation and Context

Makes the text easier to read.

### CODE REVIEW

**Comment by hugovk** [comment]
You're welcome!

**Comment by hugovk** [comment]
@AmitKumarDas You're welcome! How do I apply for the Hacktoberfest tshirt? Thanks!

**Comment by AmitKumarDas** [comment]
@hugovk can you please get into openebs slack and can just say hi in contributors channel. Nisanta from our team will take it up. I am anyways reporting this to hackoberfest team.

**Comment by NisantaSahoo** [comment]
@hugovk Thanks for taking part in Hacktoberfest 2019. Please fill up this form to claim your swag https://hubs.ly/H0l5ldm0

**Comment by hugovk** [comment]
Done, thank you!

**Pull request merged**
