### PR TITLE
Update oep-template.md

### PR DESCRIPTION
**Pull request by kichloo**
This is the commit message

Signed-off-by: Vishal Kichloo vishalkichloo9@gmail.com

### CODE REVIEW

**Comment by Akshay-Nagle** [comment]
Go to Checks -> There are some commands given, copy those command ->Open git bash/GitHub Desktop ->Then go to your local repo and run those earlier copied commands

Reference: https://github.com/openebs/openebs/pull/3237#issuecomment-706715407

**Comment by kichloo** [comment]
Thanks for your comment. But,incidentally, I am using Github Desktop only right now. If there's any way by this, pl list!

**Comment by kichloo** [comment]
@prateekpandey14 Kindly review the PR

**Review by prateekpandey14 — APPROVED** [review]

**Comment by kichloo** [comment]
@prateekpandey14 Although I have written the DCO command, it's not working. Is it necessary to do it or no problem?

**Comment by prateekpandey14** [comment]
Thank you @kichloo to fix this. If you are raising a change PR from the browser, paste the signature in body of the PR.
Anyways i have added your signature while sqush merge the PR.

You can sign up for Hacktoberfest swag from MayaData by entering details here: https://github.com/mayadata-io/swag/issues/new/choose

**Comment by kichloo** [comment]
@prateekpandey14 Although I had filled the Swag form months ago, I haven't received any package.

**Pull request merged**
