### PR TITLE
Update git-cheatsheet.md

### PR DESCRIPTION
**Pull request by gorlapraveen**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by muratkars** [comment]
Hi @gorlapraveen. Thanks for your PR. 
Could you please add Developer Certificate of Origin (DCO) to your PR as described here: [https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md](https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md)
and a brief description.

**Comment by gorlapraveen** [comment]
Signed-off-by: gorlapraveen <gorlapraveen@gmalil>

**Comment by gorlapraveen** [comment]
Signed-off-by:  gorlapraveen <gorlapraveen@gmail.com>

**Comment by gorlapraveen** [comment]
Hey, @muratkars . I signed DCO, Please check integration

**Comment by princerachit** [comment]
Closing this PR as the DCO is missing. Feel free to raise another PR after fixing the issue.

**Pull request closed without merging**
