### PR TITLE
Consider Gitlab,BitBucket accounts  for Hacktoberfest2020  pull requests of openebs and  Litmus chaos Repos

### PR DESCRIPTION
**Pull request by drraghavendra**
Provide the authentication details of Gitlab ,BitBucket accounts of openebs mayadata for Hacktoberfest2020

### CODE REVIEW

**Comment by drraghavendra** [comment]
@drraghavendra 14 @kmova please add relevant labels to this issue.

**Comment by drraghavendra** [comment]
Signed-off-by  @drraghavendra   <drraghavendra99@gmail.com>

**Comment by drraghavendra** [comment]
Signed-off by @drraghavendra  <drraghavendra99@gmail.com>

**Comment by kmova** [comment]
@drraghavendra - OpenEBS currently only supports GitHub. The process for contributoring can be found in https://github.com/openebs/openebs/blob/master/CONTRIBUTING.md

While we appreciate the feedback, the right channel to provide this feedback is via issue or slack message. So closing this PR.

**Pull request closed without merging**
