### PR TITLE
PEP 8 and String formatting

### PR DESCRIPTION
**Pull request by vkmrishad**
Signed-off-by: vkmrishad <mohammedrishad.vk@gmail.com>

- PEP 8 fixes
- String Formatting

### CODE REVIEW

**Comment by vkmrishad** [comment]
@ksatchit Thank you

**Comment by shiveshabhishek** [comment]
lgtm

**Comment by ashishranjan738** [comment]
Can you resolve the conflicts @vkmrishad ?

**Comment by vkmrishad** [comment]
@ashishranjan738 
Conflict fixed.

**Comment by vkmrishad** [comment]
@shiveshabhishek @ashishranjan738 @ksatchit 
PR can be merged.

**Comment by vkmrishad** [comment]
@ksatchit 
Thank you

**Pull request merged**
