### PR TITLE
Fix indentation for k8s/vagrant/1.9.4/ubuntu/Vagrantfile

### LINKED ISSUE #312: Fix mix-indent in Vagrantfile openebs repo
Some Vagrantfiles across our repos have mixed indentation.
Find them and fix them. One per commit and one per PR.

Prerequisites:
- some working knowledge of git & vagrant

Helpful points
- Run `vagrant validate` to see if the `Vagrantfile` is okay.

Congratulations on your :1st_place_medal: PR.

### LINKED ISSUE #1513: BUG REPORT : Partial solution for issue #312
##  BUG REPORT 
 
A BUG REPORT 

**What happened**:
With respect to Issue #312 , the indentation in openebs/k8s/lib/vagrant/test/k8s/1.9.4/ubuntu/Vagarantfile is mixed and it should be standardized.

**What you expected to happen**:
Better Indentation

**How to reproduce it (as minimally and precisely as possible)**:
openebs/k8s/lib/vagrant/test/k8s/1.9.4/ubuntu/Vagarantfile is not as per proper indentation standards

### PR DESCRIPTION
**Pull request by garuna-m6**
**What this PR does / why we need it**:
A partial solution to the indentation errors in the code 

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #1513 

**Special notes for your reviewer**:
Resolves most spacing issues

### CODE REVIEW

**Comment by kmova** [comment]
@garuna-m6 - After the changes, where you able to run this Vagrantfile?

**Comment by garuna-m6** [comment]
yes , on my ubuntu machine i was able to run it , is it causing some issues ?

**Comment by nsathyaseelan** [comment]
@kmova @garuna-m6 This Vagrantfile is LGTM
Able to run and bring up the vagarnt vms.
```
devops@devops-virtual-machine:~/k8s-demo/pr15$ vagrant status
Current machine states:

kubemaster-01             running (virtualbox)
kubeminion-01             running (virtualbox)
kubeminion-02             running (virtualbox)
```

**Comment by NisantaSahoo** [comment]
Congratulations @dinukadesilva  for your PR getting merged! Thanks for taking part in OpenEBS Hackfest.
Fill up the doc form to get the Hackfest T-Shirt and Swags
https://docs.google.com/spreadsheets/d/1TZYIdERnD72YPeUsdS5hDfI6xgXXCax4-DHpXh-o6r0/edit?usp=sharing
Looking for some more awesome contributions from you and win more prizes

**Pull request merged**
