### PR TITLE
[FIX] Markdown syntax in all Contribution Guidelines

### PR DESCRIPTION
**Pull request by sambhav2612**
**What this PR does / why we need it**: This PR intends to refactor the several contribution guidelines from the perspective of removing extra and redundancies in the written markdowns affecting the overall OpenEBS documentation. 

**Which issue this PR fixes**: This PR does not consider any open issue in reference.

**Special notes for your reviewer**: I know this PR looks big at a glance but the changes are more inclined towards improvements on the future contributions as well for better overall documentation with clear contribution guidelines.

### CODE REVIEW

**Comment by sambhav2612** [comment]
@utkarshmani1997 @kmova @yudaykiran Please review.

**Comment by sambhav2612** [comment]
@ksatchit please review.

**Comment by sambhav2612** [comment]
Would anyone please review this PR, it has been almost 7 days and I've had found several other issues in documentation waiting for this PR to get somewhere ahead.

**Comment by NisantaSahoo** [comment]
Thanks for raising the PR @sambhav2612. The review will be done in next 24 hrs

**Comment by NisantaSahoo** [comment]
Congratulations @sambhav2612  for your PR getting merged! Thanks for taking part in OpenEBS Hackfest.
Fill up the doc form to get the Hackfest T-Shirt and Swags
https://docs.google.com/spreadsheets/d/1TZYIdERnD72YPeUsdS5hDfI6xgXXCax4-DHpXh-o6r0/edit?usp=sharing
Looking for some more awesome contributions from you and win more prizes !!

**Pull request merged**
