### PR TITLE
Removing files which are already moved to docs.openebs.io

### PR DESCRIPTION
**Pull request by omi10859**
Signed-off-by: omkar <omkar10859@gmail.com>

**What this PR does / why we need it**: 
Deleting files which are already moved to doc.openebs.io 

**Which issue this PR fixes**:  
https://github.com/openebs/openebs/issues/563

### CODE REVIEW

**Comment by omi10859** [comment]
@NisantaSahoo please review this

**Comment by armudgal** [comment]
Do we have any update on this @omi10859.

**Comment by omi10859** [comment]
If you wish to continue the work go ahead @armudgal

**Comment by kmova** [comment]
This PR needs some work. Closing this PR to allow new contributor to pick up the issue.

**Pull request closed without merging**
