### PR TITLE
Added script for #442

### LINKED ISSUE #442: git scripts that can help setup/contribute to openebs
The development or contributors work-flow requires the developer running multiple git commands for setting up forked repo, creating dev branches, syncing the dev branches with upstream master etc., 

The tools can be hosted under : *openebs/contribute/tools*

Some sample scripts can be like:

- setup_remote <reponame>
```
#reponame can be either provided as arugment or auto-detected from *git config remote.origin.url*
git remote add upstream https://github.com/openebs/$reponame
git remote set-url --push upstream no_push
git remote -v
```

- sync_with_master

```
git checkout master
git fetch upstream master
git rebase upstream/master
git status
git push origin master
```

### PR DESCRIPTION
**Pull request by Logan1x**
**What this PR does / why we need it**: for issue #442 

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #442 

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by Logan1x** [comment]
`May be you can add the code to auto-detect as well as part of the next PR.`
can you elaborate this?

**Comment by kmova** [comment]
the current setup-remote.sh expects that user provide $reponame

assume the following steps:
```
mkdir -p openebs
cd openebs
git clone https://github.com/kmova/openebs.git
cd openebs
```

After performing above steps, user will have to manually set $reponame=openebs and then run setup-remote.sh. Instead, if user runs setup-remote.sh from within openebs directory, the script can auto -detect the repo name.

**Comment by Logan1x** [comment]
But I don't know how to do that can you guide me?

**Comment by Logan1x** [comment]
http://bit.ly/2zQoW3s Is this news is true? are you providing special edition hacktoberfest t-shirt?

**Comment by nitisuryawanshi** [comment]
@Logan1x Yes it is true, will you please email me the address you want the t shirt to be shipped to, and I will get this processed right away. <niti.suryawanshi@openebs.io>

**Comment by Logan1x** [comment]
Done😊.

**Pull request merged**
