### PR TITLE
fix: Grammatical correction in documentation file 

### PR DESCRIPTION
**Pull request by idivyanshbansal**
#3472

### CODE REVIEW

**Comment by idivyanshbansal** [comment]
error: failed to push some refs to 'https://github.com/idivyanshbansal/openebs' 
This comes in DCO

**Review by akhilerm — CHANGES_REQUESTED** [review]
Some changes are required in a few of the files.

**Comment by akhilerm** [comment]
@idivyanshbansal .
The following changes are not needed:
1. https://github.com/openebs/openebs/pull/3473/files#diff-53337bf7ea91d782c573ac8653c18f95b7b23c38da9de08288639bcec9993406R7
2. https://github.com/openebs/openebs/pull/3473/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R43
3. https://github.com/openebs/openebs/pull/3473/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R71
4. https://github.com/openebs/openebs/pull/3473/files#diff-2b1b69303b927a484e02c7fad9fc87d0d3ff0dc22ae1da0ecd0dc935d922a23cR10. (/set-up/setup/)
5. https://github.com/openebs/openebs/pull/3473/files#diff-f6ed156e4bf5c791680662464b94ea5d753f219ee816b385f67870e2c0d7d4c7R15


The ROADMAP.md file has now changed and its contents need to be updated with [this](https://github.com/openebs/openebs/wiki/ROADMAP-updates)

**Comment by akhilerm** [comment]
@idivyanshbansal The roadmap file has changed. Can you rebase and push the changes?

**Pull request closed without merging**
